#!/usr/bin/env python3
"""Generate and locally preview the GitHub Pages site."""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import webbrowser
from functools import partial
from http.server import SimpleHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path

from roc_version import require_pinned_roc

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / "target" / "www-preview"
MARKER = ".basic-ssg-www-preview"


class QuietHandler(SimpleHTTPRequestHandler):
    def log_message(self, format: str, *args: object) -> None:
        print(f"HTTP: {format % args}")


def executable(command: str) -> str:
    path = Path(command)
    if path.is_absolute() or path.parent != Path("."):
        candidate = path if path.is_absolute() else ROOT / path
        resolved = str(candidate.resolve()) if candidate.is_file() else None
    else:
        resolved = shutil.which(command)
    if resolved is None:
        raise SystemExit(f"Could not find Roc executable {command!r}. Use --roc or add roc to PATH.")
    return resolved


def run(*args: str | Path, env: dict[str, str] | None = None) -> None:
    command = [str(value) for value in args]
    print(f"+ {subprocess.list2cmdline(command)}", flush=True)
    subprocess.run(command, cwd=ROOT, env=env, check=True)


def prepare_output(output: Path) -> None:
    if output.exists():
        if not (output / MARKER).is_file():
            raise SystemExit(f"Refusing to replace {output}: it was not created by this script")
        shutil.rmtree(output)
    output.mkdir(parents=True)
    (output / MARKER).write_text("generated by scripts/serve_www.py\n", encoding="utf-8")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--roc", default=os.environ.get("ROC", "roc"))
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=8000)
    parser.add_argument("--with-releases", action="store_true", help="include versioned docs from GitHub release assets")
    parser.add_argument("--no-open", action="store_true")
    parser.add_argument("--no-serve", action="store_true", help="generate the site and exit")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    if not 0 <= args.port <= 65535:
        raise SystemExit("--port must be between 0 and 65535")
    roc = executable(args.roc)
    require_pinned_roc(roc)
    output = args.output.resolve()
    prepare_output(output)
    shutil.copytree(ROOT / "www", output, dirs_exist_ok=True)
    if args.with_releases:
        run("python3", ROOT / "scripts" / "restore_release_docs.py", output)
    env = os.environ.copy()
    env["ROC_DOCS_URL_ROOT"] = "/main"
    run(roc, "docs", f"--output={output / 'main'}", ROOT / "platform" / "main.roc", env=env)
    run("python3", ROOT / "scripts" / "enhance_docs_site.py", output)
    if args.no_serve:
        print(f"Generated Pages site: {output}")
        return

    handler = partial(QuietHandler, directory=str(output))
    try:
        server = ThreadingHTTPServer((args.host, args.port), handler)
    except OSError as error:
        raise SystemExit(f"Could not listen on {args.host}:{args.port}: {error}") from None
    server.daemon_threads = True
    host, port = server.server_address[:2]
    display_host = "127.0.0.1" if host in {"0.0.0.0", "::"} else host
    if ":" in display_host:
        display_host = f"[{display_host}]"
    url = f"http://{display_host}:{port}/"
    print(f"Serving {output} at {url}")
    if not args.no_open and not webbrowser.open(url):
        print("Could not open a browser automatically; open the URL above.")
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nStopping server.")
    finally:
        server.server_close()


if __name__ == "__main__":
    try:
        main()
    except subprocess.CalledProcessError as error:
        raise SystemExit(error.returncode) from None
