//! Roc Platform ABI
//!
//! This file defines the Rust interface for hosted functions in a Roc platform.
//! It is automatically generated by the Roc glue generator.
//!
//! Hosted argument ownership:
//! - Roc transfers ownership of refcounted arguments to the hosted function.
//! - The hosted function must decref owned refcounted arguments when done.
//! - If the host stores or returns an argument, it must retain or transfer ownership explicitly.
//!
//! Import this module from the platform host and implement the listed hosted symbols
//! with the exact natural C ABI signatures shown below.

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(dead_code)]

use core::ffi::c_void;
use core::sync::atomic::{AtomicIsize, Ordering};
use std::alloc::Layout;

/// Runtime representation of an opaque `Box(T)` value.
pub type RocBox = *mut c_void;

/// Host-internal allocator and diagnostic context used by helper functions in this file.
///
/// Compiled Roc code does not receive this value. The real host ABI is the set of direct
/// linker symbols declared below (`roc_alloc`, hosted symbols, and provided entrypoints).
#[repr(C)]
pub struct RocHost {
    pub env: *mut c_void,
    pub roc_alloc: extern "C" fn(*mut RocHost, usize, usize) -> *mut c_void,
    pub roc_dealloc: extern "C" fn(*mut RocHost, *mut c_void, usize),
    pub roc_realloc: extern "C" fn(*mut RocHost, *mut c_void, usize, usize) -> *mut c_void,
    pub roc_dbg: extern "C" fn(*mut RocHost, *const u8, usize),
    pub roc_expect_failed: extern "C" fn(*mut RocHost, *const u8, usize),
    pub roc_crashed: extern "C" fn(*mut RocHost, *const u8, usize),
}

impl RocHost {
    /// Allocate memory with the given alignment and length.
    ///
    /// # Safety
    /// The returned pointer must be used only according to Roc allocation layout
    /// rules and later released through the matching host deallocator.
    #[inline]
    pub unsafe fn alloc(&self, alignment: usize, length: usize) -> *mut c_void {
        let host = self as *const RocHost as *mut RocHost;
        (self.roc_alloc)(host, length, alignment)
    }

    /// Deallocate memory previously allocated with `alloc`.
    ///
    /// # Safety
    /// `ptr` must have been allocated by this host with the same alignment and must
    /// not be used after this call.
    #[inline]
    pub unsafe fn dealloc(&self, ptr: *mut c_void, alignment: usize) {
        let host = self as *const RocHost as *mut RocHost;
        (self.roc_dealloc)(host, ptr, alignment);
    }

    /// Reallocate memory to a new size.
    ///
    /// # Safety
    /// `old_ptr` must have been allocated by this host with the same alignment.
    /// The returned pointer replaces `old_ptr`; the old pointer must not be used.
    #[inline]
    pub unsafe fn realloc(
        &self,
        old_ptr: *mut c_void,
        alignment: usize,
        new_length: usize,
    ) -> *mut c_void {
        let host = self as *const RocHost as *mut RocHost;
        (self.roc_realloc)(host, old_ptr, new_length, alignment)
    }
}

/// Uniform ABI function pointer stored in `RocErasedCallablePayload`.
pub type RocErasedCallableFn = extern "C" fn(*mut RocHost, *mut u8, *const u8, *mut u8);

/// Final-drop callback for inline erased-callable captures.
pub type RocErasedCallableOnDrop = extern "C" fn(*mut u8, *mut RocHost);

/// Payload header for `Box(function)`.
#[repr(C)]
#[derive(Debug, Clone, Copy)]
pub struct RocErasedCallablePayload {
    pub callable_fn_ptr: RocErasedCallableFn,
    pub on_drop: Option<RocErasedCallableOnDrop>,
}

/// Runtime representation of `Box(function)`.
pub type RocErasedCallable = *mut u8;

pub const ROC_ERASED_CALLABLE_CAPTURE_ALIGNMENT: usize = 16;
pub const ROC_ERASED_CALLABLE_PAYLOAD_ALIGNMENT: usize = 16;
pub const ROC_ERASED_CALLABLE_CAPTURE_OFFSET: usize =
    (core::mem::size_of::<RocErasedCallablePayload>() + 15) & !15;

#[inline]
pub const fn roc_erased_callable_payload_size(capture_size: usize) -> usize {
    ROC_ERASED_CALLABLE_CAPTURE_OFFSET + capture_size
}

#[inline]
/// # Safety
/// `callable` must be a non-null Roc erased-callable data pointer.
pub unsafe fn roc_erased_callable_payload_ptr(callable: RocErasedCallable) -> *mut RocErasedCallablePayload {
    callable as *mut RocErasedCallablePayload
}

#[inline]
/// # Safety
/// `callable` must be a non-null Roc erased-callable data pointer.
pub unsafe fn roc_erased_callable_capture_ptr(callable: RocErasedCallable) -> *mut u8 {
    callable.add(ROC_ERASED_CALLABLE_CAPTURE_OFFSET)
}

/// Allocate a Roc erased callable payload.
///
/// # Safety
/// The caller must initialize and use the returned callable according to Roc's
/// erased-callable ABI. `callable_fn_ptr` and `on_drop` must have matching ABI
/// signatures for the captured payload.
pub unsafe fn roc_erased_callable_allocate(
    roc_host: &RocHost,
    callable_fn_ptr: RocErasedCallableFn,
    on_drop: Option<RocErasedCallableOnDrop>,
    capture_size: usize,
) -> RocErasedCallable {
    let ptr_width = core::mem::size_of::<usize>();
    let alignment = core::cmp::max(ptr_width, ROC_ERASED_CALLABLE_PAYLOAD_ALIGNMENT);
    let extra_bytes = core::cmp::max(ptr_width, ROC_ERASED_CALLABLE_PAYLOAD_ALIGNMENT);
    let base = roc_host.alloc(alignment, extra_bytes + roc_erased_callable_payload_size(capture_size)) as *mut u8;
    let data = base.add(extra_bytes);
    let rc = data.sub(core::mem::size_of::<isize>()) as *mut isize;
    *rc = 1;
    let payload = roc_erased_callable_payload_ptr(data);
    *payload = RocErasedCallablePayload { callable_fn_ptr, on_drop };
    data
}

/// Payload drop callback for a boxed value.
///
/// The callback receives the boxed payload data pointer and must recursively
/// decref any Roc refcounted values inside the payload. It must not free the
/// box allocation; `decref_box_with` and `free_box_with` free it after the callback.
pub type RocBoxPayloadDecref = extern "C" fn(*mut c_void, *mut RocHost);

/// Increment the refcount of a boxed payload data pointer.
pub fn incref_box(data_ptr: RocBox, amount: isize) {
    let data = match box_data_ptr(data_ptr) {
        Some(ptr) => ptr,
        None => return,
    };
    let rc = box_refcount_ptr(data);
    unsafe {
        if (*rc).load(Ordering::Relaxed) == 0 {
            return; // REFCOUNT_STATIC_DATA
        }
        (*rc).fetch_add(amount, Ordering::Relaxed);
    }
}

/// Allocate a Roc box and return a pointer to its payload data.
pub fn allocate_box(
    payload_size: usize,
    payload_alignment: usize,
    payload_contains_refcounted: bool,
    roc_host: &RocHost,
) -> RocBox {
    let ptr_width = core::mem::size_of::<usize>();
    let required_space = if payload_contains_refcounted { 2 * ptr_width } else { ptr_width };
    let header_bytes = required_space.max(payload_alignment);
    let alloc_alignment = ptr_width.max(payload_alignment);
    let base = unsafe { roc_host.alloc(alloc_alignment, header_bytes + payload_size) } as *mut u8;
    let data = unsafe { base.add(header_bytes) };
    unsafe {
        let rc = data.sub(core::mem::size_of::<isize>()) as *mut isize;
        *rc = 1;
    }
    data as RocBox
}

/// Decrement a pointer-aligned boxed payload with no Roc refcounted values.
pub fn decref_box(data_ptr: RocBox, roc_host: &RocHost) {
    decref_box_with(data_ptr, core::mem::align_of::<usize>(), false, None, roc_host);
}

/// Increment a boxed function closure.
pub fn incref_erased_callable(callable: RocErasedCallable, amount: isize) {
    incref_box(callable as RocBox, amount);
}

/// Decrement a boxed function closure and run its capture drop callback on final release.
pub fn decref_erased_callable(callable: RocErasedCallable, roc_host: &RocHost) {
    decref_box_with(
        callable as RocBox,
        ROC_ERASED_CALLABLE_PAYLOAD_ALIGNMENT,
        false,
        Some(drop_erased_callable_payload),
        roc_host,
    );
}

extern "C" fn drop_erased_callable_payload(data_ptr: *mut c_void, roc_host: *mut RocHost) {
    if data_ptr.is_null() || roc_host.is_null() {
        return;
    }
    unsafe {
        let callable = data_ptr as RocErasedCallable;
        let payload = roc_erased_callable_payload_ptr(callable);
        if let Some(on_drop) = (*payload).on_drop {
            on_drop(roc_erased_callable_capture_ptr(callable), roc_host);
        }
    }
}

/// Decrement a boxed payload and run payload teardown when this is the final ref.
///
/// `payload_contains_refcounted` must match the value passed to `allocate_box`:
/// it determines the box header size, and is independent of whether a
/// `payload_decref` teardown callback is supplied. A host resource handle such
/// as `Box(U64)` holding a raw pointer has `payload_contains_refcounted: false`
/// even when it provides a teardown callback to free the underlying resource.
pub fn decref_box_with(
    data_ptr: RocBox,
    payload_alignment: usize,
    payload_contains_refcounted: bool,
    payload_decref: Option<RocBoxPayloadDecref>,
    roc_host: &RocHost,
) {
    let data = match box_data_ptr(data_ptr) {
        Some(ptr) => ptr,
        None => return,
    };
    let rc = box_refcount_ptr(data);
    unsafe {
        if (*rc).load(Ordering::Relaxed) == 0 {
            return; // REFCOUNT_STATIC_DATA
        }
        let prev = (*rc).fetch_sub(1, Ordering::Relaxed);
        if prev == 1 {
            if let Some(callback) = payload_decref {
                callback(data_ptr, roc_host as *const RocHost as *mut RocHost);
            }
            free_box_allocation(data, payload_alignment, payload_contains_refcounted, roc_host);
        }
    }
}

/// Free a boxed payload allocation immediately after running payload teardown.
///
/// See `decref_box_with` for the meaning of `payload_contains_refcounted`.
pub fn free_box_with(
    data_ptr: RocBox,
    payload_alignment: usize,
    payload_contains_refcounted: bool,
    payload_decref: Option<RocBoxPayloadDecref>,
    roc_host: &RocHost,
) {
    let data = match box_data_ptr(data_ptr) {
        Some(ptr) => ptr,
        None => return,
    };
    if let Some(callback) = payload_decref {
        callback(data_ptr, roc_host as *const RocHost as *mut RocHost);
    }
    free_box_allocation(data, payload_alignment, payload_contains_refcounted, roc_host);
}

/// Return true when a boxed payload data pointer has exactly one live ref.
pub fn is_unique_box(data_ptr: RocBox) -> bool {
    let data = match box_data_ptr(data_ptr) {
        Some(ptr) => ptr,
        None => return true,
    };
    let rc = box_refcount_ptr(data);
    unsafe { (*rc).load(Ordering::Relaxed) == 1 }
}

fn box_data_ptr(data_ptr: RocBox) -> Option<*mut u8> {
    if data_ptr.is_null() {
        None
    } else {
        Some(data_ptr as *mut u8)
    }
}

fn box_refcount_ptr(data: *mut u8) -> *mut AtomicIsize {
    unsafe { data.sub(core::mem::size_of::<isize>()) as *mut AtomicIsize }
}

fn free_box_allocation(
    data: *mut u8,
    payload_alignment: usize,
    payload_contains_refcounted: bool,
    roc_host: &RocHost,
) {
    let ptr_width = core::mem::size_of::<usize>();
    let required_space = if payload_contains_refcounted { 2 * ptr_width } else { ptr_width };
    let header_bytes = required_space.max(payload_alignment);
    let alloc_alignment = ptr_width.max(payload_alignment);
    let base = unsafe { data.sub(header_bytes) } as *mut c_void;
    unsafe {
        roc_host.dealloc(base, alloc_alignment);
    }
}

/// A Roc string value. Small strings (up to 23 bytes on 64-bit) are stored inline;
/// larger strings are heap-allocated with a reference count.
///
/// `bytes` is never tagged. Operations, host code, glue code, and object-file
/// relocations can use it directly as the UTF-8 byte pointer for non-small
/// strings. Seamless-slice tagging lives in `capacity_or_alloc_ptr` instead.
/// Big-string capacity is stored shifted left by one bit, so max capacity is
/// essentially `isize::MAX` bytes: about 2 GiB on 32-bit targets and 8 EiB on
/// 64-bit targets.
///
/// This type is ABI-compatible with the Zig RocStr (24 bytes, `#[repr(C)]`).
#[repr(C)]
#[derive(Clone, Copy)]
pub struct RocStr {
    pub bytes: *mut u8,
    pub capacity_or_alloc_ptr: usize,
    pub length: usize,
}

const ROC_STR_SIZE: usize = core::mem::size_of::<RocStr>();
const ROC_SMALL_STR_MAX_LEN: usize = ROC_STR_SIZE - 1;
const ROC_SMALL_STR_BIT: usize = isize::MIN as usize;
const ROC_SEAMLESS_SLICE_TAG: usize = 1;

impl RocStr {
    /// Return an empty RocStr (small string with zero length).
    pub fn empty() -> Self {
        Self {
            bytes: core::ptr::null_mut(),
            capacity_or_alloc_ptr: 0,
            length: ROC_SMALL_STR_BIT,
        }
    }

    /// Return true if this string is stored inline (small string optimization).
    #[inline]
    pub fn is_small_str(&self) -> bool {
        (self.length as isize) < 0
    }

    /// Return true if this string is a seamless slice into another allocation.
    #[inline]
    pub fn is_seamless_slice(&self) -> bool {
        !self.is_small_str() && (self.capacity_or_alloc_ptr & ROC_SEAMLESS_SLICE_TAG) != 0
    }

    /// Return the length of the string in bytes.
    #[inline]
    pub fn len(&self) -> usize {
        if self.is_small_str() {
            let bytes_ptr = self as *const Self as *const u8;
            let last_byte = unsafe { *bytes_ptr.add(ROC_STR_SIZE - 1) };
            (last_byte ^ 0b1000_0000) as usize
        } else {
            self.length
        }
    }

    /// Return true if the string has zero length.
    #[inline]
    pub fn is_empty(&self) -> bool {
        self.len() == 0
    }

    /// Return the string contents as a byte slice.
    pub fn as_slice(&self) -> &[u8] {
        let ptr = self.as_u8_ptr();
        unsafe { core::slice::from_raw_parts(ptr, self.len()) }
    }

    /// Return a pointer to the raw UTF-8 bytes.
    #[inline]
    pub fn as_u8_ptr(&self) -> *const u8 {
        if self.is_small_str() {
            self as *const Self as *const u8
        } else {
            self.bytes as *const u8
        }
    }

    /// Return the string contents as a `&str`, assuming valid UTF-8.
    pub fn as_str(&self) -> &str {
        // SAFETY: Roc guarantees all strings are valid UTF-8.
        unsafe { core::str::from_utf8_unchecked(self.as_slice()) }
    }

    /// Create a RocStr from a byte slice, using `roc_host` for heap allocation if needed.
    pub fn from_slice(slice: &[u8], roc_host: &RocHost) -> Self {
        if slice.len() < ROC_STR_SIZE {
            let mut result = Self::empty();
            let ptr = &mut result as *mut Self as *mut u8;
            unsafe {
                core::ptr::copy_nonoverlapping(slice.as_ptr(), ptr, slice.len());
                *ptr.add(ROC_STR_SIZE - 1) = (slice.len() as u8) | 0b1000_0000;
            }
            result
        } else {
            let ptr_width = core::mem::size_of::<usize>();
            let total = ptr_width + slice.len();
            let base = unsafe { roc_host.alloc(core::mem::align_of::<usize>(), total) };
            let data_ptr = unsafe { (base as *mut u8).add(ptr_width) };
            // Write refcount = 1
            unsafe {
                let rc = (data_ptr as *mut isize).sub(1);
                *rc = 1;
                core::ptr::copy_nonoverlapping(slice.as_ptr(), data_ptr, slice.len());
            }
            Self {
                bytes: data_ptr,
                capacity_or_alloc_ptr: slice.len() << 1,
                length: slice.len(),
            }
        }
    }

    /// Create a RocStr from a `&str`.
    pub fn from_str(s: &str, roc_host: &RocHost) -> Self {
        Self::from_slice(s.as_bytes(), roc_host)
    }

    /// Decrement the reference count; frees the allocation when it reaches zero.
    pub fn decref(&self, roc_host: &RocHost) {
        if self.is_small_str() {
            return;
        }
        let alloc_ptr = self.get_allocation_ptr();
        if alloc_ptr.is_null() {
            return;
        }
        unsafe {
            let rc = (alloc_ptr as *mut AtomicIsize).sub(1);
            if (*rc).load(Ordering::Relaxed) == 0 {
                return; // REFCOUNT_STATIC_DATA — bytes are in read-only memory
            }
            let prev = (*rc).fetch_sub(1, Ordering::Relaxed);
            if prev == 1 {
                let ptr_width = core::mem::size_of::<usize>();
                let base = alloc_ptr.sub(ptr_width) as *mut c_void;
                roc_host.dealloc(base, core::mem::align_of::<usize>());
            }
        }
    }

    /// Increment the reference count by `amount`.
    pub fn incref(&self, amount: isize) {
        if self.is_small_str() {
            return;
        }
        let alloc_ptr = self.get_allocation_ptr();
        if alloc_ptr.is_null() {
            return;
        }
        unsafe {
            let rc = (alloc_ptr as *mut AtomicIsize).sub(1);
            if (*rc).load(Ordering::Relaxed) == 0 {
                return; // REFCOUNT_STATIC_DATA
            }
            (*rc).fetch_add(amount, Ordering::Relaxed);
        }
    }

    /// Return true if this string has a reference count of exactly one.
    pub fn is_unique(&self) -> bool {
        if self.is_small_str() {
            return true;
        }
        let alloc_ptr = self.get_allocation_ptr();
        if alloc_ptr.is_null() {
            return true;
        }
        unsafe {
            let rc = (alloc_ptr as *const AtomicIsize).sub(1);
            let count = (*rc).load(Ordering::Relaxed);
            count == 0 || count == 1
        }
    }

    fn get_allocation_ptr(&self) -> *mut u8 {
        if self.is_seamless_slice() {
            (self.capacity_or_alloc_ptr & !ROC_SEAMLESS_SLICE_TAG) as *mut u8
        } else {
            self.bytes
        }
    }
}

impl core::fmt::Debug for RocStr {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.debug_struct("RocStr")
            .field("value", &self.as_str())
            .field("len", &self.len())
            .field("is_small", &self.is_small_str())
            .finish()
    }
}

/// A generic Roc list. Elements are reference-counted and heap-allocated.
///
/// When `ELEMENTS_REFCOUNTED` is true (the default via `RocList<T>`), an extra
/// `ptr_width` bytes are reserved in the allocation header for the element count,
/// matching the Roc runtime's `allocateWithRefcount` layout.
pub type RocList<T> = RocListWith<T, true>;

/// Parameterized list constructor; use `RocList<T>` for refcounted elements.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct RocListWith<T, const ELEMENTS_REFCOUNTED: bool> {
    pub elements: *mut T,
    pub length: usize,
    pub capacity_or_alloc_ptr: usize,
}

impl<T, const ELEMENTS_REFCOUNTED: bool> RocListWith<T, ELEMENTS_REFCOUNTED> {
    #[inline]
    fn header_bytes() -> usize {
        let ptr_width = core::mem::size_of::<usize>();
        let required_space = if ELEMENTS_REFCOUNTED { 2 * ptr_width } else { ptr_width };
        required_space.max(core::mem::align_of::<T>())
    }

    /// Return an empty RocList.
    pub fn empty() -> Self {
        Self {
            elements: core::ptr::null_mut(),
            length: 0,
            capacity_or_alloc_ptr: 0,
        }
    }

    /// Return the number of elements in the list.
    #[inline]
    pub fn len(&self) -> usize {
        self.length
    }

    /// Return true if the list has zero elements.
    #[inline]
    pub fn is_empty(&self) -> bool {
        self.length == 0
    }

    /// Return true if this list is a seamless slice into another allocation.
    /// Slices share the rc slot with their backing allocation; the alloc ptr is
    /// encoded in `capacity_or_alloc_ptr` with the low bit set.
    #[inline]
    pub fn is_seamless_slice(&self) -> bool {
        (self.capacity_or_alloc_ptr & 1) != 0
    }

    /// Resolve `self` to the start of its backing allocation (the element block
    /// just after the rc slot). Returns `null` for empty lists. Handles both
    /// whole-backing and seamless-slice forms.
    fn get_allocation_ptr(&self) -> *mut u8 {
        if self.is_seamless_slice() {
            (self.capacity_or_alloc_ptr & !1) as *mut u8
        } else {
            self.elements as *mut u8
        }
    }

    fn allocation_element_count(&self) -> usize {
        if self.is_seamless_slice() && ELEMENTS_REFCOUNTED {
            let alloc_ptr = self.get_allocation_ptr();
            if alloc_ptr.is_null() {
                return 0;
            }
            unsafe {
                let ptr = alloc_ptr as *const usize;
                *ptr.sub(2)
            }
        } else {
            self.length
        }
    }

    /// Return the list elements as a slice.
    pub fn as_slice(&self) -> &[T] {
        if self.elements.is_null() {
            &[]
        } else {
            unsafe { core::slice::from_raw_parts(self.elements, self.length) }
        }
    }

    /// Return all items in the backing allocation, not just this slice.
    pub fn allocation_items(&self) -> &[T] {
        if self.elements.is_null() {
            &[]
        } else {
            unsafe { core::slice::from_raw_parts(self.get_allocation_ptr() as *const T, self.allocation_element_count()) }
        }
    }

    /// Allocate a new list with space for `length` elements.
    pub fn allocate(length: usize, roc_host: &RocHost) -> Self {
        if length == 0 {
            return Self::empty();
        }
        let align = core::mem::align_of::<T>().max(core::mem::align_of::<usize>());
        let header_bytes = Self::header_bytes();
        let data_bytes = length * core::mem::size_of::<T>();
        let total = data_bytes + header_bytes;
        let base = unsafe { roc_host.alloc(align, total) };
        let data_ptr = unsafe { (base as *mut u8).add(header_bytes) };
        // Write refcount = 1
        unsafe {
            let rc = (data_ptr as *mut isize).sub(1);
            *rc = 1;
        }
        Self {
            elements: data_ptr as *mut T,
            length,
            capacity_or_alloc_ptr: length << 1,
        }
    }

    /// Create a RocList from a slice, copying elements into a new allocation.
    pub fn from_slice(slice: &[T], roc_host: &RocHost) -> Self where T: Copy {
        if slice.is_empty() {
            return Self::empty();
        }
        let list = Self::allocate(slice.len(), roc_host);
        unsafe {
            core::ptr::copy_nonoverlapping(
                slice.as_ptr(),
                list.elements,
                slice.len(),
            );
        }
        list
    }

    /// Decrement the reference count; frees the allocation when it reaches zero.
    pub fn decref(&self, roc_host: &RocHost) {
        if self.elements.is_null() {
            return;
        }
        let alloc_ptr = self.get_allocation_ptr();
        if alloc_ptr.is_null() {
            return;
        }
        let align = core::mem::align_of::<T>().max(core::mem::align_of::<usize>());
        let header_bytes = Self::header_bytes();
        unsafe {
            let rc = (alloc_ptr as *mut AtomicIsize).sub(1);
            if (*rc).load(Ordering::Relaxed) == 0 {
                return; // REFCOUNT_STATIC_DATA — elements are in read-only memory
            }
            let prev = (*rc).fetch_sub(1, Ordering::Relaxed);
            if prev == 1 {
                let base = alloc_ptr.sub(header_bytes) as *mut c_void;
                roc_host.dealloc(base, align);
            }
        }
    }

    /// Increment the reference count by `amount`.
    pub fn incref(&self, amount: isize) {
        if self.elements.is_null() {
            return;
        }
        let alloc_ptr = self.get_allocation_ptr();
        if alloc_ptr.is_null() {
            return;
        }
        unsafe {
            let rc = (alloc_ptr as *mut AtomicIsize).sub(1);
            if (*rc).load(Ordering::Relaxed) == 0 {
                return; // REFCOUNT_STATIC_DATA
            }
            (*rc).fetch_add(amount, Ordering::Relaxed);
        }
    }

    /// Return true if this list has a reference count of exactly one.
    pub fn is_unique(&self) -> bool {
        let alloc_ptr = self.get_allocation_ptr();
        if alloc_ptr.is_null() {
            return true;
        }
        unsafe {
            let rc = (alloc_ptr as *const AtomicIsize).sub(1);
            let count = (*rc).load(Ordering::Relaxed);
            count == 0 || count == 1
        }
    }

    /// Return true if this list's allocation has exactly one counted ref.
    pub fn has_one_ref(&self) -> bool {
        let alloc_ptr = self.get_allocation_ptr();
        if alloc_ptr.is_null() {
            return false;
        }
        unsafe {
            let rc = (alloc_ptr as *const AtomicIsize).sub(1);
            (*rc).load(Ordering::Relaxed) == 1
        }
    }
}

impl<T: core::fmt::Debug, const ELEMENTS_REFCOUNTED: bool> core::fmt::Debug for RocListWith<T, ELEMENTS_REFCOUNTED> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.debug_list().entries(self.as_slice().iter()).finish()
    }
}

/// Element type for __AnonStruct5
#[repr(C)]
#[derive(Clone, Copy)]
pub struct AnonStruct5 {
    pub args: RocList<RocStr>,
    pub envs: RocList<RocStr>,
    pub program: RocStr,
    pub clear_envs: bool,
}

const _: () = assert!(core::mem::size_of::<AnonStruct5>() == 80, "AnonStruct5 size mismatch");
const _: () = assert!(core::mem::align_of::<AnonStruct5>() == 8, "AnonStruct5 alignment mismatch");

/// Element type for __AnonStruct8
#[repr(C)]
#[derive(Clone, Copy)]
pub struct AnonStruct8 {
    pub stderr: RocListWith<u8, false>,
    pub stdout: RocListWith<u8, false>,
    pub exit_code: i32,
}

const _: () = assert!(core::mem::size_of::<AnonStruct8>() == 56, "AnonStruct8 size mismatch");
const _: () = assert!(core::mem::align_of::<AnonStruct8>() == 8, "AnonStruct8 alignment mismatch");

/// Element type for __AnonStruct14
#[repr(C)]
#[derive(Clone, Copy)]
pub struct AnonStruct14 {
    pub _0: RocStr,
    pub _1: RocStr,
}

const _: () = assert!(core::mem::size_of::<AnonStruct14>() == 48, "AnonStruct14 size mismatch");
const _: () = assert!(core::mem::align_of::<AnonStruct14>() == 8, "AnonStruct14 alignment mismatch");

/// Element type for __AnonStruct15
#[repr(C)]
#[derive(Clone, Copy)]
pub struct AnonStruct15 {
    pub arch: RocStr,
    pub os: RocStr,
}

const _: () = assert!(core::mem::size_of::<AnonStruct15>() == 48, "AnonStruct15 size mismatch");
const _: () = assert!(core::mem::align_of::<AnonStruct15>() == 8, "AnonStruct15 alignment mismatch");

/// Element type for __AnonStruct21
#[repr(C)]
#[derive(Clone, Copy)]
pub struct AnonStruct21 {
    pub output_path: UnixBytesOrWindowsU16s,
    pub source_path: UnixBytesOrWindowsU16s,
    pub url: RocStr,
}

const _: () = assert!(core::mem::size_of::<AnonStruct21>() == 88, "AnonStruct21 size mismatch");
const _: () = assert!(core::mem::align_of::<AnonStruct21>() == 8, "AnonStruct21 alignment mismatch");

/// Tag discriminant for Try.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TryType0Tag {
    Err = 0,
    Ok = 1,
}

/// Tag union: Try
#[repr(C)]
#[derive(Clone, Copy)]
pub struct TryType0 {
    pub payload: TryType0Payload,
    pub tag: TryType0Tag,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union TryType0Payload {
    pub err: core::mem::ManuallyDrop<IOErr>,
    pub ok: core::mem::ManuallyDrop<i32>,
}

const _: () = assert!(core::mem::size_of::<TryType0>() == 40, "TryType0 size mismatch");
const _: () = assert!(core::mem::align_of::<TryType0>() == 8, "TryType0 alignment mismatch");

/// Tag discriminant for IOErr.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum IOErrTag {
    AlreadyExists = 0,
    BrokenPipe = 1,
    Interrupted = 2,
    NotFound = 3,
    Other = 4,
    OutOfMemory = 5,
    PermissionDenied = 6,
    Unsupported = 7,
}

/// Tag union: IOErr
#[repr(C)]
#[derive(Clone, Copy)]
pub struct IOErr {
    pub payload: IOErrPayload,
    pub tag: IOErrTag,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union IOErrPayload {
    pub already_exists: [u8; 0],
    pub broken_pipe: [u8; 0],
    pub interrupted: [u8; 0],
    pub not_found: [u8; 0],
    pub other: core::mem::ManuallyDrop<RocStr>,
    pub out_of_memory: [u8; 0],
    pub permission_denied: [u8; 0],
    pub unsupported: [u8; 0],
}

const _: () = assert!(core::mem::size_of::<IOErr>() == 32, "IOErr size mismatch");
const _: () = assert!(core::mem::align_of::<IOErr>() == 8, "IOErr alignment mismatch");

/// Tag discriminant for Try.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TryType11Tag {
    Err = 0,
    Ok = 1,
}

/// Tag union: Try
#[repr(C)]
#[derive(Clone, Copy)]
pub struct TryType11 {
    pub payload: TryType11Payload,
    pub tag: TryType11Tag,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union TryType11Payload {
    pub err: core::mem::ManuallyDrop<RocStr>,
    pub ok: core::mem::ManuallyDrop<RocStr>,
}

const _: () = assert!(core::mem::size_of::<TryType11>() == 32, "TryType11 size mismatch");
const _: () = assert!(core::mem::align_of::<TryType11>() == 8, "TryType11 alignment mismatch");

/// Tag discriminant for Try.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TryType16Tag {
    Err = 0,
    Ok = 1,
}

/// Tag union: Try
#[repr(C)]
#[derive(Clone, Copy)]
pub struct TryType16 {
    pub payload: TryType16Payload,
    pub tag: TryType16Tag,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union TryType16Payload {
    pub err: core::mem::ManuallyDrop<*mut c_void>,
    pub ok: core::mem::ManuallyDrop<RocStr>,
}

const _: () = assert!(core::mem::size_of::<TryType16>() == 32, "TryType16 size mismatch");
const _: () = assert!(core::mem::align_of::<TryType16>() == 8, "TryType16 alignment mismatch");

/// Tag discriminant for Try.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TryType18Tag {
    Err = 0,
    Ok = 1,
}

/// Tag union: Try
#[repr(C)]
#[derive(Clone, Copy)]
pub struct TryType18 {
    pub payload: TryType18Payload,
    pub tag: TryType18Tag,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union TryType18Payload {
    pub err: core::mem::ManuallyDrop<RocStr>,
    pub ok: core::mem::ManuallyDrop<RocList<AnonStruct21>>,
}

const _: () = assert!(core::mem::size_of::<TryType18>() == 32, "TryType18 size mismatch");
const _: () = assert!(core::mem::align_of::<TryType18>() == 8, "TryType18 alignment mismatch");

/// Tag discriminant for UnixBytesOrWindowsU16s.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum UnixBytesOrWindowsU16sTag {
    UnixBytes = 0,
    WindowsU16s = 1,
}

/// Tag union: UnixBytesOrWindowsU16s
#[repr(C)]
#[derive(Clone, Copy)]
pub struct UnixBytesOrWindowsU16s {
    pub payload: UnixBytesOrWindowsU16sPayload,
    pub tag: UnixBytesOrWindowsU16sTag,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union UnixBytesOrWindowsU16sPayload {
    pub unix_bytes: core::mem::ManuallyDrop<RocListWith<u8, false>>,
    pub windows_u16s: core::mem::ManuallyDrop<RocListWith<u16, false>>,
}

const _: () = assert!(core::mem::size_of::<UnixBytesOrWindowsU16s>() == 32, "UnixBytesOrWindowsU16s size mismatch");
const _: () = assert!(core::mem::align_of::<UnixBytesOrWindowsU16s>() == 8, "UnixBytesOrWindowsU16s alignment mismatch");

/// Tag discriminant for Try.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TryType25Tag {
    Err = 0,
    Ok = 1,
}

/// Tag union: Try
#[repr(C)]
#[derive(Clone, Copy)]
pub struct TryType25 {
    pub payload: TryType25Payload,
    pub tag: TryType25Tag,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union TryType25Payload {
    pub err: core::mem::ManuallyDrop<RocStr>,
    pub ok: core::mem::ManuallyDrop<RocStr>,
}

const _: () = assert!(core::mem::size_of::<TryType25>() == 32, "TryType25 size mismatch");
const _: () = assert!(core::mem::align_of::<TryType25>() == 8, "TryType25 alignment mismatch");

/// Tag discriminant for Try.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TryType27Tag {
    Err = 0,
    Ok = 1,
}

/// Tag union: Try
#[repr(C)]
#[derive(Clone, Copy)]
pub struct TryType27 {
    pub payload: TryType27Payload,
    pub tag: TryType27Tag,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union TryType27Payload {
    pub err: core::mem::ManuallyDrop<RocStr>,
    pub ok: core::mem::ManuallyDrop<()>,
}

const _: () = assert!(core::mem::size_of::<TryType27>() == 32, "TryType27 size mismatch");
const _: () = assert!(core::mem::align_of::<TryType27>() == 8, "TryType27 alignment mismatch");

/// Tag discriminant for Try.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TryType30Tag {
    Err = 0,
    Ok = 1,
}

/// Tag union: Try
#[repr(C)]
#[derive(Clone, Copy)]
pub struct TryType30 {
    pub payload: TryType30Payload,
    pub tag: TryType30Tag,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union TryType30Payload {
    pub err: core::mem::ManuallyDrop<IOErr>,
    pub ok: core::mem::ManuallyDrop<()>,
}

const _: () = assert!(core::mem::size_of::<TryType30>() == 40, "TryType30 size mismatch");
const _: () = assert!(core::mem::align_of::<TryType30>() == 8, "TryType30 alignment mismatch");

/// Tag discriminant for Try.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TryType32Tag {
    Err = 0,
    Ok = 1,
}

/// Tag union: Try
#[repr(C)]
#[derive(Clone, Copy)]
pub struct TryType32 {
    pub payload: TryType32Payload,
    pub tag: TryType32Tag,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union TryType32Payload {
    pub err: core::mem::ManuallyDrop<IOErr>,
    pub ok: core::mem::ManuallyDrop<()>,
}

const _: () = assert!(core::mem::size_of::<TryType32>() == 40, "TryType32 size mismatch");
const _: () = assert!(core::mem::align_of::<TryType32>() == 8, "TryType32 alignment mismatch");

/// Tag discriminant for Try.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TryType38Tag {
    Err = 0,
    Ok = 1,
}

/// Tag union: Try
#[repr(C)]
#[derive(Clone, Copy)]
pub struct TryType38 {
    pub payload: TryType38Payload,
    pub tag: TryType38Tag,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union TryType38Payload {
    pub err: core::mem::ManuallyDrop<i32>,
    pub ok: core::mem::ManuallyDrop<()>,
}

const _: () = assert!(core::mem::size_of::<TryType38>() == 8, "TryType38 size mismatch");
const _: () = assert!(core::mem::align_of::<TryType38>() == 4, "TryType38 alignment mismatch");

/// Return type record for Host.cmd_output!
/// Fields ordered by alignment descending (Roc ABI)
#[repr(C)]
#[derive(Clone, Copy)]
pub struct HostCmdOutputRetRecord {
    pub stderr: RocListWith<u8, false>,
    pub stdout: RocListWith<u8, false>,
    pub exit_code: i32,
}

const _: () = assert!(core::mem::size_of::<HostCmdOutputRetRecord>() == 56, "HostCmdOutputRetRecord size mismatch");
const _: () = assert!(core::mem::align_of::<HostCmdOutputRetRecord>() == 8, "HostCmdOutputRetRecord alignment mismatch");

/// Return type record for Host.env_arch_os!
/// Fields ordered by alignment descending (Roc ABI)
#[repr(C)]
#[derive(Clone, Copy)]
pub struct HostEnvArchOsRetRecord {
    pub arch: RocStr,
    pub os: RocStr,
}

const _: () = assert!(core::mem::size_of::<HostEnvArchOsRetRecord>() == 48, "HostEnvArchOsRetRecord size mismatch");
const _: () = assert!(core::mem::align_of::<HostEnvArchOsRetRecord>() == 8, "HostEnvArchOsRetRecord alignment mismatch");

/// Arguments for Host.cmd_output!
/// Roc signature: { args : List(Str), clear_envs : Bool, envs : List(Str), program : Str } => { exit_code : I32, stderr : List(U8), stdout : List(U8) }
/// Refcounted fields are owned by the hosted function.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct HostCmdOutputArgs {
    pub args: RocList<RocStr>,
    pub envs: RocList<RocStr>,
    pub program: RocStr,
    pub clear_envs: bool,
}

const _: () = assert!(core::mem::size_of::<HostCmdOutputArgs>() == 80, "HostCmdOutputArgs size mismatch");
const _: () = assert!(core::mem::align_of::<HostCmdOutputArgs>() == 8, "HostCmdOutputArgs alignment mismatch");

/// Arguments for Host.cmd_status!
/// Roc signature: { args : List(Str), clear_envs : Bool, envs : List(Str), program : Str } => Try(I32, [CmdError(IOErr)])
/// Refcounted fields are owned by the hosted function.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct HostCmdStatusArgs {
    pub args: RocList<RocStr>,
    pub envs: RocList<RocStr>,
    pub program: RocStr,
    pub clear_envs: bool,
}

const _: () = assert!(core::mem::size_of::<HostCmdStatusArgs>() == 80, "HostCmdStatusArgs size mismatch");
const _: () = assert!(core::mem::align_of::<HostCmdStatusArgs>() == 8, "HostCmdStatusArgs alignment mismatch");

/// Arguments for Host.env_var!
/// Roc signature: Str => Try(Str, [VarNotFound(Str)])
/// Refcounted fields are owned by the hosted function.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct HostEnvVarArgs {
    pub arg0: RocStr,
}

/// Arguments for Host.ssg_find_pages!
/// Roc signature: [UnixBytes(List(U8)), WindowsU16s(List(U16))] => Try(List({ output_path : [UnixBytes(List(U8)), WindowsU16s(List(U16))], source_path : [UnixBytes(List(U8)), WindowsU16s(List(U16))], url : Str }), [PagesError(Str)])
/// Refcounted fields are owned by the hosted function.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct HostSsgFindPagesArgs {
    pub arg0: UnixBytesOrWindowsU16s,
}

/// Arguments for Host.ssg_parse_markdown!
/// Roc signature: [UnixBytes(List(U8)), WindowsU16s(List(U16))] => Try(Str, [ParseError(Str)])
/// Refcounted fields are owned by the hosted function.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct HostSsgParseMarkdownArgs {
    pub arg0: UnixBytesOrWindowsU16s,
}

/// Arguments for Host.ssg_write_file!
/// Roc signature: [UnixBytes(List(U8)), WindowsU16s(List(U16))], [UnixBytes(List(U8)), WindowsU16s(List(U16))], Str => Try({}, [WriteError(Str)])
/// Refcounted fields are owned by the hosted function.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct HostSsgWriteFileArgs {
    pub arg0: UnixBytesOrWindowsU16s,
    pub arg1: UnixBytesOrWindowsU16s,
    pub arg2: RocStr,
}

/// Arguments for Host.stderr_line!
/// Roc signature: Str => Try({}, [StderrErr(IOErr)])
/// Refcounted fields are owned by the hosted function.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct HostStderrLineArgs {
    pub arg0: RocStr,
}

/// Arguments for Host.stderr_write!
/// Roc signature: Str => Try({}, [StderrErr(IOErr)])
/// Refcounted fields are owned by the hosted function.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct HostStderrWriteArgs {
    pub arg0: RocStr,
}

/// Arguments for Host.stdout_line!
/// Roc signature: Str => Try({}, [StdoutErr(IOErr)])
/// Refcounted fields are owned by the hosted function.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct HostStdoutLineArgs {
    pub arg0: RocStr,
}

/// Arguments for Host.stdout_write!
/// Roc signature: Str => Try({}, [StdoutErr(IOErr)])
/// Refcounted fields are owned by the hosted function.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct HostStdoutWriteArgs {
    pub arg0: RocStr,
}

// =============================================================================
// Semantic Type Aliases
// =============================================================================

pub type HostCmdOutput = AnonStruct8;
pub type HostCmdStatusResult = TryType0;
pub type HostCmdStatusResultPayload = TryType0Payload;
pub type HostCmdStatusResultTag = TryType0Tag;
pub type HostIOErr = IOErr;
pub type HostIOErrPayload = IOErrPayload;
pub type HostIOErrTag = IOErrTag;
pub type HostEnvArchOs = AnonStruct15;
pub type HostEnvDict = AnonStruct14;
pub type HostEnvVarResult = TryType11;
pub type HostEnvVarResultPayload = TryType11Payload;
pub type HostEnvVarResultTag = TryType11Tag;
pub type HostLocaleGetResult = TryType16;
pub type HostLocaleGetResultPayload = TryType16Payload;
pub type HostLocaleGetResultTag = TryType16Tag;
pub type HostSsgFindPagesResult = TryType18;
pub type HostSsgFindPagesResultPayload = TryType18Payload;
pub type HostSsgFindPagesResultTag = TryType18Tag;
pub type HostSsgFindPagesOk = AnonStruct21;
pub type HostSsgParseMarkdownResult = TryType25;
pub type HostSsgParseMarkdownResultPayload = TryType25Payload;
pub type HostSsgParseMarkdownResultTag = TryType25Tag;
pub type HostSsgWriteFileResult = TryType27;
pub type HostSsgWriteFileResultPayload = TryType27Payload;
pub type HostSsgWriteFileResultTag = TryType27Tag;
pub type HostStderrLineResult = TryType32;
pub type HostStderrLineResultPayload = TryType32Payload;
pub type HostStderrLineResultTag = TryType32Tag;
pub type HostStderrWriteResult = TryType32;
pub type HostStderrWriteResultPayload = TryType32Payload;
pub type HostStderrWriteResultTag = TryType32Tag;
pub type HostStdoutLineResult = TryType30;
pub type HostStdoutLineResultPayload = TryType30Payload;
pub type HostStdoutLineResultTag = TryType30Tag;
pub type HostStdoutWriteResult = TryType30;
pub type HostStdoutWriteResultPayload = TryType30Payload;
pub type HostStdoutWriteResultTag = TryType30Tag;

// =============================================================================
// Generated Refcount Helpers
// =============================================================================

/// Recursively decrement Roc-owned payloads in TryType0.
pub fn decref_try_type0(value: TryType0, roc_host: &RocHost) {
    let _ = roc_host;
    match value.tag {
        TryType0Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            decref_ioerr(payload, roc_host);
        },
        TryType0Tag::Ok => {},
    }
}

/// Increment Roc-owned payloads in TryType0.
pub fn incref_try_type0(value: TryType0, amount: isize) {
    let _ = amount;
    match value.tag {
        TryType0Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            incref_ioerr(payload, amount);
        },
        TryType0Tag::Ok => {},
    }
}

/// Recursively decrement Roc-owned payloads in IOErr.
pub fn decref_ioerr(value: IOErr, roc_host: &RocHost) {
    let _ = roc_host;
    match value.tag {
        IOErrTag::AlreadyExists => {},
        IOErrTag::BrokenPipe => {},
        IOErrTag::Interrupted => {},
        IOErrTag::NotFound => {},
        IOErrTag::Other => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.other);
            payload.decref(roc_host);
        },
        IOErrTag::OutOfMemory => {},
        IOErrTag::PermissionDenied => {},
        IOErrTag::Unsupported => {},
    }
}

/// Increment Roc-owned payloads in IOErr.
pub fn incref_ioerr(value: IOErr, amount: isize) {
    let _ = amount;
    match value.tag {
        IOErrTag::AlreadyExists => {},
        IOErrTag::BrokenPipe => {},
        IOErrTag::Interrupted => {},
        IOErrTag::NotFound => {},
        IOErrTag::Other => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.other);
            payload.incref(amount);
        },
        IOErrTag::OutOfMemory => {},
        IOErrTag::PermissionDenied => {},
        IOErrTag::Unsupported => {},
    }
}

/// Recursively decrement Roc-owned fields in AnonStruct5.
pub fn decref_anon_struct5(value: AnonStruct5, roc_host: &RocHost) {
    {
        let list = value.args;
        if list.has_one_ref() {
            for item_ref in list.allocation_items() {
                let item = *item_ref;
                    item.decref(roc_host);
            }
        }
        list.decref(roc_host);
    }
    {
        let list = value.envs;
        if list.has_one_ref() {
            for item_ref in list.allocation_items() {
                let item = *item_ref;
                    item.decref(roc_host);
            }
        }
        list.decref(roc_host);
    }
    value.program.decref(roc_host);
}

/// Increment Roc-owned fields in AnonStruct5.
pub fn incref_anon_struct5(value: AnonStruct5, amount: isize) {
    value.args.incref(amount);
    value.envs.incref(amount);
    value.program.incref(amount);
}

/// Recursively decrement Roc-owned fields in AnonStruct8.
pub fn decref_anon_struct8(value: AnonStruct8, roc_host: &RocHost) {
    value.stderr.decref(roc_host);
    value.stdout.decref(roc_host);
}

/// Increment Roc-owned fields in AnonStruct8.
pub fn incref_anon_struct8(value: AnonStruct8, amount: isize) {
    value.stderr.incref(amount);
    value.stdout.incref(amount);
}

/// Recursively decrement Roc-owned payloads in TryType11.
pub fn decref_try_type11(value: TryType11, roc_host: &RocHost) {
    let _ = roc_host;
    match value.tag {
        TryType11Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            payload.decref(roc_host);
        },
        TryType11Tag::Ok => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.ok);
            payload.decref(roc_host);
        },
    }
}

/// Increment Roc-owned payloads in TryType11.
pub fn incref_try_type11(value: TryType11, amount: isize) {
    let _ = amount;
    match value.tag {
        TryType11Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            payload.incref(amount);
        },
        TryType11Tag::Ok => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.ok);
            payload.incref(amount);
        },
    }
}

/// Recursively decrement Roc-owned fields in AnonStruct14.
pub fn decref_anon_struct14(value: AnonStruct14, roc_host: &RocHost) {
    value._0.decref(roc_host);
    value._1.decref(roc_host);
}

/// Increment Roc-owned fields in AnonStruct14.
pub fn incref_anon_struct14(value: AnonStruct14, amount: isize) {
    value._0.incref(amount);
    value._1.incref(amount);
}

/// Recursively decrement Roc-owned fields in AnonStruct15.
pub fn decref_anon_struct15(value: AnonStruct15, roc_host: &RocHost) {
    value.arch.decref(roc_host);
    value.os.decref(roc_host);
}

/// Increment Roc-owned fields in AnonStruct15.
pub fn incref_anon_struct15(value: AnonStruct15, amount: isize) {
    value.arch.incref(amount);
    value.os.incref(amount);
}

/// Recursively decrement Roc-owned payloads in TryType16.
pub fn decref_try_type16(value: TryType16, roc_host: &RocHost) {
    let _ = roc_host;
    match value.tag {
        TryType16Tag::Err => {},
        TryType16Tag::Ok => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.ok);
            payload.decref(roc_host);
        },
    }
}

/// Increment Roc-owned payloads in TryType16.
pub fn incref_try_type16(value: TryType16, amount: isize) {
    let _ = amount;
    match value.tag {
        TryType16Tag::Err => {},
        TryType16Tag::Ok => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.ok);
            payload.incref(amount);
        },
    }
}

/// Recursively decrement Roc-owned payloads in TryType18.
pub fn decref_try_type18(value: TryType18, roc_host: &RocHost) {
    let _ = roc_host;
    match value.tag {
        TryType18Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            payload.decref(roc_host);
        },
        TryType18Tag::Ok => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.ok);
            {
                let list = payload;
                if list.has_one_ref() {
                    for item_ref in list.allocation_items() {
                        let item = *item_ref;
                            decref_anon_struct21(item, roc_host);
                    }
                }
                list.decref(roc_host);
            }
        },
    }
}

/// Increment Roc-owned payloads in TryType18.
pub fn incref_try_type18(value: TryType18, amount: isize) {
    let _ = amount;
    match value.tag {
        TryType18Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            payload.incref(amount);
        },
        TryType18Tag::Ok => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.ok);
            payload.incref(amount);
        },
    }
}

/// Recursively decrement Roc-owned fields in AnonStruct21.
pub fn decref_anon_struct21(value: AnonStruct21, roc_host: &RocHost) {
    decref_unix_bytes_or_windows_u16s(value.output_path, roc_host);
    decref_unix_bytes_or_windows_u16s(value.source_path, roc_host);
    value.url.decref(roc_host);
}

/// Increment Roc-owned fields in AnonStruct21.
pub fn incref_anon_struct21(value: AnonStruct21, amount: isize) {
    incref_unix_bytes_or_windows_u16s(value.output_path, amount);
    incref_unix_bytes_or_windows_u16s(value.source_path, amount);
    value.url.incref(amount);
}

/// Recursively decrement Roc-owned payloads in UnixBytesOrWindowsU16s.
pub fn decref_unix_bytes_or_windows_u16s(value: UnixBytesOrWindowsU16s, roc_host: &RocHost) {
    let _ = roc_host;
    match value.tag {
        UnixBytesOrWindowsU16sTag::UnixBytes => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.unix_bytes);
            payload.decref(roc_host);
        },
        UnixBytesOrWindowsU16sTag::WindowsU16s => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.windows_u16s);
            payload.decref(roc_host);
        },
    }
}

/// Increment Roc-owned payloads in UnixBytesOrWindowsU16s.
pub fn incref_unix_bytes_or_windows_u16s(value: UnixBytesOrWindowsU16s, amount: isize) {
    let _ = amount;
    match value.tag {
        UnixBytesOrWindowsU16sTag::UnixBytes => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.unix_bytes);
            payload.incref(amount);
        },
        UnixBytesOrWindowsU16sTag::WindowsU16s => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.windows_u16s);
            payload.incref(amount);
        },
    }
}

/// Recursively decrement Roc-owned payloads in TryType25.
pub fn decref_try_type25(value: TryType25, roc_host: &RocHost) {
    let _ = roc_host;
    match value.tag {
        TryType25Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            payload.decref(roc_host);
        },
        TryType25Tag::Ok => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.ok);
            payload.decref(roc_host);
        },
    }
}

/// Increment Roc-owned payloads in TryType25.
pub fn incref_try_type25(value: TryType25, amount: isize) {
    let _ = amount;
    match value.tag {
        TryType25Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            payload.incref(amount);
        },
        TryType25Tag::Ok => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.ok);
            payload.incref(amount);
        },
    }
}

/// Recursively decrement Roc-owned payloads in TryType27.
pub fn decref_try_type27(value: TryType27, roc_host: &RocHost) {
    let _ = roc_host;
    match value.tag {
        TryType27Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            payload.decref(roc_host);
        },
        TryType27Tag::Ok => {},
    }
}

/// Increment Roc-owned payloads in TryType27.
pub fn incref_try_type27(value: TryType27, amount: isize) {
    let _ = amount;
    match value.tag {
        TryType27Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            payload.incref(amount);
        },
        TryType27Tag::Ok => {},
    }
}

/// Recursively decrement Roc-owned payloads in TryType30.
pub fn decref_try_type30(value: TryType30, roc_host: &RocHost) {
    let _ = roc_host;
    match value.tag {
        TryType30Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            decref_ioerr(payload, roc_host);
        },
        TryType30Tag::Ok => {},
    }
}

/// Increment Roc-owned payloads in TryType30.
pub fn incref_try_type30(value: TryType30, amount: isize) {
    let _ = amount;
    match value.tag {
        TryType30Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            incref_ioerr(payload, amount);
        },
        TryType30Tag::Ok => {},
    }
}

/// Recursively decrement Roc-owned payloads in TryType32.
pub fn decref_try_type32(value: TryType32, roc_host: &RocHost) {
    let _ = roc_host;
    match value.tag {
        TryType32Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            decref_ioerr(payload, roc_host);
        },
        TryType32Tag::Ok => {},
    }
}

/// Increment Roc-owned payloads in TryType32.
pub fn incref_try_type32(value: TryType32, amount: isize) {
    let _ = amount;
    match value.tag {
        TryType32Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            incref_ioerr(payload, amount);
        },
        TryType32Tag::Ok => {},
    }
}

/// Recursively decrement Roc-owned payloads in TryType38.
pub fn decref_try_type38(value: TryType38, roc_host: &RocHost) {
    let _ = roc_host;
    match value.tag {
        TryType38Tag::Err => {},
        TryType38Tag::Ok => {},
    }
}

/// Increment Roc-owned payloads in TryType38.
pub fn incref_try_type38(value: TryType38, amount: isize) {
    let _ = amount;
    match value.tag {
        TryType38Tag::Err => {},
        TryType38Tag::Ok => {},
    }
}


// =============================================================================
// Runtime Symbols
//
// The host defines these linker symbols. Compiled Roc code calls them directly.
// =============================================================================

#[allow(improper_ctypes)]
unsafe extern "C" {
    pub fn roc_alloc(length: usize, alignment: usize) -> *mut c_void;
    pub fn roc_dealloc(ptr: *mut c_void, alignment: usize);
    pub fn roc_realloc(ptr: *mut c_void, new_length: usize, alignment: usize) -> *mut c_void;
    pub fn roc_dbg(bytes: *const u8, len: usize);
    pub fn roc_expect_failed(bytes: *const u8, len: usize);
    pub fn roc_crashed(bytes: *const u8, len: usize);
}

// =============================================================================
// Hosted Symbols
//
// The platform host must export these symbols with the exact direct C ABI signatures.
// Refcounted arguments are owned by the hosted function.
// =============================================================================

#[allow(improper_ctypes)]
unsafe extern "C" {
    /// Hosted symbol for Host.cmd_output!
    /// Roc signature: { args : List(Str), clear_envs : Bool, envs : List(Str), program : Str } => { exit_code : I32, stderr : List(U8), stdout : List(U8) }
    pub fn hosted_cmd_output(arg0: HostCmdOutputArgs) -> AnonStruct8;

    /// Hosted symbol for Host.cmd_status!
    /// Roc signature: { args : List(Str), clear_envs : Bool, envs : List(Str), program : Str } => Try(I32, [CmdError(IOErr)])
    pub fn hosted_cmd_status(arg0: HostCmdStatusArgs) -> TryType0;

    /// Hosted symbol for Host.env_arch_os!
    /// Roc signature: {} => { arch : Str, os : Str }
    pub fn hosted_env_arch_os() -> AnonStruct15;

    /// Hosted symbol for Host.env_dict!
    /// Roc signature: {} => List((Str, Str))
    pub fn hosted_env_dict() -> RocList<AnonStruct14>;

    /// Hosted symbol for Host.env_var!
    /// Roc signature: Str => Try(Str, [VarNotFound(Str)])
    pub fn hosted_env_var(arg0: RocStr) -> TryType11;

    /// Hosted symbol for Host.locale_all!
    /// Roc signature: {} => List(Str)
    pub fn hosted_locale_all() -> RocList<RocStr>;

    /// Hosted symbol for Host.locale_get!
    /// Roc signature: {} => Try(Str, [NotAvailable])
    pub fn hosted_locale_get() -> TryType16;

    /// Hosted symbol for Host.ssg_find_pages!
    /// Roc signature: [UnixBytes(List(U8)), WindowsU16s(List(U16))] => Try(List({ output_path : [UnixBytes(List(U8)), WindowsU16s(List(U16))], source_path : [UnixBytes(List(U8)), WindowsU16s(List(U16))], url : Str }), [PagesError(Str)])
    pub fn hosted_ssg_find_pages(arg0: UnixBytesOrWindowsU16s) -> TryType18;

    /// Hosted symbol for Host.ssg_parse_markdown!
    /// Roc signature: [UnixBytes(List(U8)), WindowsU16s(List(U16))] => Try(Str, [ParseError(Str)])
    pub fn hosted_ssg_parse_markdown(arg0: UnixBytesOrWindowsU16s) -> TryType25;

    /// Hosted symbol for Host.ssg_write_file!
    /// Roc signature: [UnixBytes(List(U8)), WindowsU16s(List(U16))], [UnixBytes(List(U8)), WindowsU16s(List(U16))], Str => Try({}, [WriteError(Str)])
    pub fn hosted_ssg_write_file(arg0: UnixBytesOrWindowsU16s, arg1: UnixBytesOrWindowsU16s, arg2: RocStr) -> TryType27;

    /// Hosted symbol for Host.stderr_line!
    /// Roc signature: Str => Try({}, [StderrErr(IOErr)])
    pub fn hosted_stderr_line(arg0: RocStr) -> TryType32;

    /// Hosted symbol for Host.stderr_write!
    /// Roc signature: Str => Try({}, [StderrErr(IOErr)])
    pub fn hosted_stderr_write(arg0: RocStr) -> TryType32;

    /// Hosted symbol for Host.stdout_line!
    /// Roc signature: Str => Try({}, [StdoutErr(IOErr)])
    pub fn hosted_stdout_line(arg0: RocStr) -> TryType30;

    /// Hosted symbol for Host.stdout_write!
    /// Roc signature: Str => Try({}, [StdoutErr(IOErr)])
    pub fn hosted_stdout_write(arg0: RocStr) -> TryType30;

    /// Hosted symbol for Host.utc_now!
    /// Roc signature: {} => U128
    pub fn hosted_utc_now() -> u128;

}

/// Default memory management functions for Roc platform helpers.
///
/// Memory layout: each allocation prepends size metadata so that dealloc/realloc
/// can recover the original allocation size because `roc_dealloc` receives no length.
pub struct DefaultAllocators;

impl DefaultAllocators {
    /// Allocate memory using the Rust global allocator.
    pub extern "C" fn roc_alloc(_roc_host: *mut RocHost, length: usize, alignment: usize) -> *mut c_void {
        unsafe {
            let min_alignment = alignment.max(core::mem::align_of::<usize>());
            let size_storage_bytes = min_alignment;
            let total_size = length + size_storage_bytes;

            debug_assert!(min_alignment.is_power_of_two(), "alignment must be a power of two");
            let layout = Layout::from_size_align_unchecked(total_size, min_alignment);
            let base_ptr = std::alloc::alloc(layout);
            if base_ptr.is_null() {
                eprintln!("roc_alloc: out of memory");
                std::process::exit(1);
            }

            let size_ptr = base_ptr.add(size_storage_bytes).sub(core::mem::size_of::<usize>()) as *mut usize;
            *size_ptr = total_size;

            base_ptr.add(size_storage_bytes) as *mut c_void
        }
    }

    /// Free memory previously allocated by `roc_alloc`.
    pub extern "C" fn roc_dealloc(_roc_host: *mut RocHost, ptr: *mut c_void, alignment: usize) {
        unsafe {
            let min_alignment = alignment.max(core::mem::align_of::<usize>());
            let size_storage_bytes = min_alignment;

            let size_ptr = (ptr as *const u8).sub(core::mem::size_of::<usize>()) as *const usize;
            let total_size = *size_ptr;

            let base_ptr = (ptr as *mut u8).sub(size_storage_bytes);
            debug_assert!(min_alignment.is_power_of_two(), "alignment must be a power of two");
            let layout = Layout::from_size_align_unchecked(total_size, min_alignment);
            std::alloc::dealloc(base_ptr, layout);
        }
    }

    /// Reallocate memory, preserving existing user data.
    pub extern "C" fn roc_realloc(_roc_host: *mut RocHost, ptr: *mut c_void, new_length: usize, alignment: usize) -> *mut c_void {
        unsafe {
            let min_alignment = alignment.max(core::mem::align_of::<usize>());
            let size_storage_bytes = min_alignment;

            let old_size_ptr = (ptr as *const u8).sub(core::mem::size_of::<usize>()) as *const usize;
            let old_total_size = *old_size_ptr;
            let old_base_ptr = (ptr as *mut u8).sub(size_storage_bytes);

            let new_total_size = new_length + size_storage_bytes;
            debug_assert!(min_alignment.is_power_of_two(), "alignment must be a power of two");
            let old_layout = Layout::from_size_align_unchecked(old_total_size, min_alignment);
            let new_base_ptr = std::alloc::realloc(old_base_ptr, old_layout, new_total_size);
            if new_base_ptr.is_null() {
                eprintln!("roc_realloc: out of memory");
                std::process::exit(1);
            }

            let new_user_ptr = new_base_ptr.add(size_storage_bytes);
            let new_size_ptr = new_user_ptr.sub(core::mem::size_of::<usize>()) as *mut usize;
            *new_size_ptr = new_total_size;
            new_user_ptr as *mut c_void
        }
    }
}

/// Default handlers for dbg, expect-failed, and crash.
pub struct DefaultHandlers;

impl DefaultHandlers {
    /// Print a `dbg` expression to stderr.
    pub extern "C" fn roc_dbg(_roc_host: *mut RocHost, bytes: *const u8, len: usize) {
        unsafe {
            let msg = core::slice::from_raw_parts(bytes, len);
            let msg = core::str::from_utf8_unchecked(msg);
            eprintln!("[ROC DBG] {}", msg);
        }
    }

    /// Print a failed `expect` to stderr.
    pub extern "C" fn roc_expect_failed(_roc_host: *mut RocHost, bytes: *const u8, len: usize) {
        unsafe {
            let msg = core::slice::from_raw_parts(bytes, len);
            let msg = core::str::from_utf8_unchecked(msg);
            eprintln!("[ROC EXPECT] {}", msg);
        }
    }

    /// Print a `crash` message to stderr and exit.
    pub extern "C" fn roc_crashed(_roc_host: *mut RocHost, bytes: *const u8, len: usize) {
        unsafe {
            let msg = core::slice::from_raw_parts(bytes, len);
            let msg = core::str::from_utf8_unchecked(msg);
            eprintln!("[ROC CRASHED] {}", msg);
            std::process::exit(1);
        }
    }
}

/// Create a host-internal helper context with default memory management and handlers.
///
/// This is only for helper functions in this generated file. It is not passed to
/// compiled Roc code, which uses the direct symbol ABI declared above.
pub fn make_roc_host(env: *mut c_void) -> RocHost {
    RocHost {
        env,
        roc_alloc: DefaultAllocators::roc_alloc,
        roc_dealloc: DefaultAllocators::roc_dealloc,
        roc_realloc: DefaultAllocators::roc_realloc,
        roc_dbg: DefaultHandlers::roc_dbg,
        roc_expect_failed: DefaultHandlers::roc_expect_failed,
        roc_crashed: DefaultHandlers::roc_crashed,
    }
}

// =============================================================================
// Provided Symbols
//
// Roc exports these symbols from the app with their natural C ABI signatures.
// =============================================================================

#[allow(improper_ctypes)]
unsafe extern "C" {
    /// Entrypoint: main_for_host!
    pub fn roc_main(arg0: RocList<RocStr>) -> i32;

}
