//! Roc Platform ABI
//!
//! This file defines the Rust interface for hosted functions in a Roc platform.
//! It is automatically generated by the Roc glue generator.
//!
//! Hosted argument ownership:
//! - Roc transfers ownership of refcounted arguments to the hosted function.
//! - The hosted function must decref owned refcounted arguments when done.
//! - If the host stores or returns an argument, it must retain or transfer ownership explicitly.
//!
//! Import this module from the platform host and implement the listed hosted symbols
//! with the exact natural C ABI signatures shown below.

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(dead_code)]

use core::ffi::c_void;
use core::sync::atomic::{AtomicIsize, Ordering};
use std::alloc::Layout;

/// Runtime representation of an opaque `Box(T)` value.
pub type RocBox = *mut c_void;

/// Host-internal allocator and diagnostic context used by helper functions in this file.
///
/// Compiled Roc code does not receive this value. The real host ABI is the set of direct
/// linker symbols declared below (`roc_alloc`, hosted symbols, and provided entrypoints).
#[repr(C)]
pub struct RocHost {
    pub env: *mut c_void,
    pub roc_alloc: extern "C" fn(*mut RocHost, usize, usize) -> *mut c_void,
    pub roc_dealloc: extern "C" fn(*mut RocHost, *mut c_void, usize),
    pub roc_realloc: extern "C" fn(*mut RocHost, *mut c_void, usize, usize) -> *mut c_void,
    pub roc_dbg: extern "C" fn(*mut RocHost, *const u8, usize),
    pub roc_expect_failed: extern "C" fn(*mut RocHost, *const u8, usize),
    pub roc_crashed: extern "C" fn(*mut RocHost, *const u8, usize),
}

impl RocHost {
    /// Allocate memory with the given alignment and length.
    ///
    /// # Safety
    /// The returned pointer must be used only according to Roc allocation layout
    /// rules and later released through the matching host deallocator.
    #[inline]
    pub unsafe fn alloc(&self, alignment: usize, length: usize) -> *mut c_void {
        let host = self as *const RocHost as *mut RocHost;
        (self.roc_alloc)(host, length, alignment)
    }

    /// Deallocate memory previously allocated with `alloc`.
    ///
    /// # Safety
    /// `ptr` must have been allocated by this host with the same alignment and must
    /// not be used after this call.
    #[inline]
    pub unsafe fn dealloc(&self, ptr: *mut c_void, alignment: usize) {
        let host = self as *const RocHost as *mut RocHost;
        (self.roc_dealloc)(host, ptr, alignment);
    }

    /// Reallocate memory to a new size.
    ///
    /// # Safety
    /// `old_ptr` must have been allocated by this host with the same alignment.
    /// The returned pointer replaces `old_ptr`; the old pointer must not be used.
    #[inline]
    pub unsafe fn realloc(
        &self,
        old_ptr: *mut c_void,
        alignment: usize,
        new_length: usize,
    ) -> *mut c_void {
        let host = self as *const RocHost as *mut RocHost;
        (self.roc_realloc)(host, old_ptr, new_length, alignment)
    }
}

/// Uniform ABI function pointer stored in `RocErasedCallablePayload`.
pub type RocErasedCallableFn = extern "C" fn(*mut RocHost, *mut u8, *const u8, *mut u8);

/// Final-drop callback for inline erased-callable captures.
pub type RocErasedCallableOnDrop = extern "C" fn(*mut u8, *mut RocHost);

/// Payload header for `Box(function)`.
#[repr(C)]
#[derive(Debug, Clone, Copy)]
pub struct RocErasedCallablePayload {
    pub callable_fn_ptr: RocErasedCallableFn,
    pub on_drop: Option<RocErasedCallableOnDrop>,
}

/// Runtime representation of `Box(function)`.
pub type RocErasedCallable = *mut u8;

pub const ROC_ERASED_CALLABLE_CAPTURE_ALIGNMENT: usize = 16;
pub const ROC_ERASED_CALLABLE_PAYLOAD_ALIGNMENT: usize = 16;
pub const ROC_ERASED_CALLABLE_CAPTURE_OFFSET: usize =
    (core::mem::size_of::<RocErasedCallablePayload>() + 15) & !15;

#[inline]
pub const fn roc_erased_callable_payload_size(capture_size: usize) -> usize {
    ROC_ERASED_CALLABLE_CAPTURE_OFFSET + capture_size
}

#[inline]
/// # Safety
/// `callable` must be a non-null Roc erased-callable data pointer.
pub unsafe fn roc_erased_callable_payload_ptr(callable: RocErasedCallable) -> *mut RocErasedCallablePayload {
    callable as *mut RocErasedCallablePayload
}

#[inline]
/// # Safety
/// `callable` must be a non-null Roc erased-callable data pointer.
pub unsafe fn roc_erased_callable_capture_ptr(callable: RocErasedCallable) -> *mut u8 {
    callable.add(ROC_ERASED_CALLABLE_CAPTURE_OFFSET)
}

/// Allocate a Roc erased callable payload.
///
/// # Safety
/// The caller must initialize and use the returned callable according to Roc's
/// erased-callable ABI. `callable_fn_ptr` and `on_drop` must have matching ABI
/// signatures for the captured payload.
pub unsafe fn roc_erased_callable_allocate(
    roc_host: &RocHost,
    callable_fn_ptr: RocErasedCallableFn,
    on_drop: Option<RocErasedCallableOnDrop>,
    capture_size: usize,
) -> RocErasedCallable {
    let ptr_width = core::mem::size_of::<usize>();
    let alignment = core::cmp::max(ptr_width, ROC_ERASED_CALLABLE_PAYLOAD_ALIGNMENT);
    let extra_bytes = core::cmp::max(ptr_width, ROC_ERASED_CALLABLE_PAYLOAD_ALIGNMENT);
    let base = roc_host.alloc(alignment, extra_bytes + roc_erased_callable_payload_size(capture_size)) as *mut u8;
    let data = base.add(extra_bytes);
    let rc = data.sub(core::mem::size_of::<isize>()) as *mut isize;
    *rc = 1;
    let payload = roc_erased_callable_payload_ptr(data);
    *payload = RocErasedCallablePayload { callable_fn_ptr, on_drop };
    data
}

/// Payload drop callback for a boxed value.
///
/// The callback receives the boxed payload data pointer and must recursively
/// decref any Roc refcounted values inside the payload. It must not free the
/// box allocation; `decref_box_with` and `free_box_with` free it after the callback.
pub type RocBoxPayloadDecref = extern "C" fn(*mut c_void, *mut RocHost);

/// Increment the refcount of a boxed payload data pointer.
pub fn incref_box(data_ptr: RocBox, amount: isize) {
    let data = match box_data_ptr(data_ptr) {
        Some(ptr) => ptr,
        None => return,
    };
    let rc = box_refcount_ptr(data);
    unsafe {
        if (*rc).load(Ordering::Relaxed) == 0 {
            return; // REFCOUNT_STATIC_DATA
        }
        (*rc).fetch_add(amount, Ordering::Relaxed);
    }
}

/// Allocate a Roc box and return a pointer to its payload data.
pub fn allocate_box(
    payload_size: usize,
    payload_alignment: usize,
    payload_contains_refcounted: bool,
    roc_host: &RocHost,
) -> RocBox {
    let ptr_width = core::mem::size_of::<usize>();
    let required_space = if payload_contains_refcounted { 2 * ptr_width } else { ptr_width };
    let header_bytes = required_space.max(payload_alignment);
    let alloc_alignment = ptr_width.max(payload_alignment);
    let base = unsafe { roc_host.alloc(alloc_alignment, header_bytes + payload_size) } as *mut u8;
    let data = unsafe { base.add(header_bytes) };
    unsafe {
        let rc = data.sub(core::mem::size_of::<isize>()) as *mut isize;
        *rc = 1;
    }
    data as RocBox
}

/// Decrement a pointer-aligned boxed payload with no Roc refcounted values.
pub fn decref_box(data_ptr: RocBox, roc_host: &RocHost) {
    decref_box_with(data_ptr, core::mem::align_of::<usize>(), false, None, roc_host);
}

/// Increment a boxed function closure.
pub fn incref_erased_callable(callable: RocErasedCallable, amount: isize) {
    incref_box(callable as RocBox, amount);
}

/// Decrement a boxed function closure and run its capture drop callback on final release.
pub fn decref_erased_callable(callable: RocErasedCallable, roc_host: &RocHost) {
    decref_box_with(
        callable as RocBox,
        ROC_ERASED_CALLABLE_PAYLOAD_ALIGNMENT,
        false,
        Some(drop_erased_callable_payload),
        roc_host,
    );
}

extern "C" fn drop_erased_callable_payload(data_ptr: *mut c_void, roc_host: *mut RocHost) {
    if data_ptr.is_null() || roc_host.is_null() {
        return;
    }
    unsafe {
        let callable = data_ptr as RocErasedCallable;
        let payload = roc_erased_callable_payload_ptr(callable);
        if let Some(on_drop) = (*payload).on_drop {
            on_drop(roc_erased_callable_capture_ptr(callable), roc_host);
        }
    }
}

/// Decrement a boxed payload and run payload teardown when this is the final ref.
///
/// `payload_contains_refcounted` must match the value passed to `allocate_box`:
/// it determines the box header size, and is independent of whether a
/// `payload_decref` teardown callback is supplied. A host resource handle such
/// as `Box(U64)` holding a raw pointer has `payload_contains_refcounted: false`
/// even when it provides a teardown callback to free the underlying resource.
pub fn decref_box_with(
    data_ptr: RocBox,
    payload_alignment: usize,
    payload_contains_refcounted: bool,
    payload_decref: Option<RocBoxPayloadDecref>,
    roc_host: &RocHost,
) {
    let data = match box_data_ptr(data_ptr) {
        Some(ptr) => ptr,
        None => return,
    };
    let rc = box_refcount_ptr(data);
    unsafe {
        if (*rc).load(Ordering::Relaxed) == 0 {
            return; // REFCOUNT_STATIC_DATA
        }
        let prev = (*rc).fetch_sub(1, Ordering::Relaxed);
        if prev == 1 {
            if let Some(callback) = payload_decref {
                callback(data_ptr, roc_host as *const RocHost as *mut RocHost);
            }
            free_box_allocation(data, payload_alignment, payload_contains_refcounted, roc_host);
        }
    }
}

/// Free a boxed payload allocation immediately after running payload teardown.
///
/// See `decref_box_with` for the meaning of `payload_contains_refcounted`.
pub fn free_box_with(
    data_ptr: RocBox,
    payload_alignment: usize,
    payload_contains_refcounted: bool,
    payload_decref: Option<RocBoxPayloadDecref>,
    roc_host: &RocHost,
) {
    let data = match box_data_ptr(data_ptr) {
        Some(ptr) => ptr,
        None => return,
    };
    if let Some(callback) = payload_decref {
        callback(data_ptr, roc_host as *const RocHost as *mut RocHost);
    }
    free_box_allocation(data, payload_alignment, payload_contains_refcounted, roc_host);
}

/// Return true when a boxed payload data pointer has exactly one live ref.
pub fn is_unique_box(data_ptr: RocBox) -> bool {
    let data = match box_data_ptr(data_ptr) {
        Some(ptr) => ptr,
        None => return true,
    };
    let rc = box_refcount_ptr(data);
    unsafe { (*rc).load(Ordering::Relaxed) == 1 }
}

fn box_data_ptr(data_ptr: RocBox) -> Option<*mut u8> {
    if data_ptr.is_null() {
        None
    } else {
        Some(data_ptr as *mut u8)
    }
}

fn box_refcount_ptr(data: *mut u8) -> *mut AtomicIsize {
    unsafe { data.sub(core::mem::size_of::<isize>()) as *mut AtomicIsize }
}

fn free_box_allocation(
    data: *mut u8,
    payload_alignment: usize,
    payload_contains_refcounted: bool,
    roc_host: &RocHost,
) {
    let ptr_width = core::mem::size_of::<usize>();
    let required_space = if payload_contains_refcounted { 2 * ptr_width } else { ptr_width };
    let header_bytes = required_space.max(payload_alignment);
    let alloc_alignment = ptr_width.max(payload_alignment);
    let base = unsafe { data.sub(header_bytes) } as *mut c_void;
    unsafe {
        roc_host.dealloc(base, alloc_alignment);
    }
}

/// A Roc string value. Small strings (up to 23 bytes on 64-bit) are stored inline;
/// larger strings are heap-allocated with a reference count.
///
/// `bytes` is never tagged. Operations, host code, glue code, and object-file
/// relocations can use it directly as the UTF-8 byte pointer for non-small
/// strings. Seamless-slice tagging lives in `capacity_or_alloc_ptr` instead.
/// Big-string capacity is stored shifted left by one bit, so max capacity is
/// essentially `isize::MAX` bytes: about 2 GiB on 32-bit targets and 8 EiB on
/// 64-bit targets.
///
/// This type is ABI-compatible with the Zig RocStr (24 bytes, `#[repr(C)]`).
#[repr(C)]
#[derive(Clone, Copy)]
pub struct RocStr {
    pub bytes: *mut u8,
    pub capacity_or_alloc_ptr: usize,
    pub length: usize,
}

const ROC_STR_SIZE: usize = core::mem::size_of::<RocStr>();
const ROC_SMALL_STR_MAX_LEN: usize = ROC_STR_SIZE - 1;
const ROC_SMALL_STR_BIT: usize = isize::MIN as usize;
const ROC_SEAMLESS_SLICE_TAG: usize = 1;

impl RocStr {
    /// Return an empty RocStr (small string with zero length).
    pub fn empty() -> Self {
        Self {
            bytes: core::ptr::null_mut(),
            capacity_or_alloc_ptr: 0,
            length: ROC_SMALL_STR_BIT,
        }
    }

    /// Return true if this string is stored inline (small string optimization).
    #[inline]
    pub fn is_small_str(&self) -> bool {
        (self.length as isize) < 0
    }

    /// Return true if this string is a seamless slice into another allocation.
    #[inline]
    pub fn is_seamless_slice(&self) -> bool {
        !self.is_small_str() && (self.capacity_or_alloc_ptr & ROC_SEAMLESS_SLICE_TAG) != 0
    }

    /// Return the length of the string in bytes.
    #[inline]
    pub fn len(&self) -> usize {
        if self.is_small_str() {
            let bytes_ptr = self as *const Self as *const u8;
            let last_byte = unsafe { *bytes_ptr.add(ROC_STR_SIZE - 1) };
            (last_byte ^ 0b1000_0000) as usize
        } else {
            self.length
        }
    }

    /// Return true if the string has zero length.
    #[inline]
    pub fn is_empty(&self) -> bool {
        self.len() == 0
    }

    /// Return the string contents as a byte slice.
    pub fn as_slice(&self) -> &[u8] {
        let ptr = self.as_u8_ptr();
        unsafe { core::slice::from_raw_parts(ptr, self.len()) }
    }

    /// Return a pointer to the raw UTF-8 bytes.
    #[inline]
    pub fn as_u8_ptr(&self) -> *const u8 {
        if self.is_small_str() {
            self as *const Self as *const u8
        } else {
            self.bytes as *const u8
        }
    }

    /// Return the string contents as a `&str`, assuming valid UTF-8.
    pub fn as_str(&self) -> &str {
        // SAFETY: Roc guarantees all strings are valid UTF-8.
        unsafe { core::str::from_utf8_unchecked(self.as_slice()) }
    }

    /// Create a RocStr from a byte slice, using `roc_host` for heap allocation if needed.
    pub fn from_slice(slice: &[u8], roc_host: &RocHost) -> Self {
        if slice.len() < ROC_STR_SIZE {
            let mut result = Self::empty();
            let ptr = &mut result as *mut Self as *mut u8;
            unsafe {
                core::ptr::copy_nonoverlapping(slice.as_ptr(), ptr, slice.len());
                *ptr.add(ROC_STR_SIZE - 1) = (slice.len() as u8) | 0b1000_0000;
            }
            result
        } else {
            let ptr_width = core::mem::size_of::<usize>();
            let total = ptr_width + slice.len();
            let base = unsafe { roc_host.alloc(core::mem::align_of::<usize>(), total) };
            let data_ptr = unsafe { (base as *mut u8).add(ptr_width) };
            // Write refcount = 1
            unsafe {
                let rc = (data_ptr as *mut isize).sub(1);
                *rc = 1;
                core::ptr::copy_nonoverlapping(slice.as_ptr(), data_ptr, slice.len());
            }
            Self {
                bytes: data_ptr,
                capacity_or_alloc_ptr: slice.len() << 1,
                length: slice.len(),
            }
        }
    }

    /// Create a RocStr from a `&str`.
    pub fn from_str(s: &str, roc_host: &RocHost) -> Self {
        Self::from_slice(s.as_bytes(), roc_host)
    }

    /// Decrement the reference count; frees the allocation when it reaches zero.
    pub fn decref(&self, roc_host: &RocHost) {
        if self.is_small_str() {
            return;
        }
        let alloc_ptr = self.get_allocation_ptr();
        if alloc_ptr.is_null() {
            return;
        }
        unsafe {
            let rc = (alloc_ptr as *mut AtomicIsize).sub(1);
            if (*rc).load(Ordering::Relaxed) == 0 {
                return; // REFCOUNT_STATIC_DATA — bytes are in read-only memory
            }
            let prev = (*rc).fetch_sub(1, Ordering::Relaxed);
            if prev == 1 {
                let ptr_width = core::mem::size_of::<usize>();
                let base = alloc_ptr.sub(ptr_width) as *mut c_void;
                roc_host.dealloc(base, core::mem::align_of::<usize>());
            }
        }
    }

    /// Increment the reference count by `amount`.
    pub fn incref(&self, amount: isize) {
        if self.is_small_str() {
            return;
        }
        let alloc_ptr = self.get_allocation_ptr();
        if alloc_ptr.is_null() {
            return;
        }
        unsafe {
            let rc = (alloc_ptr as *mut AtomicIsize).sub(1);
            if (*rc).load(Ordering::Relaxed) == 0 {
                return; // REFCOUNT_STATIC_DATA
            }
            (*rc).fetch_add(amount, Ordering::Relaxed);
        }
    }

    /// Return true if this string has a reference count of exactly one.
    pub fn is_unique(&self) -> bool {
        if self.is_small_str() {
            return true;
        }
        let alloc_ptr = self.get_allocation_ptr();
        if alloc_ptr.is_null() {
            return true;
        }
        unsafe {
            let rc = (alloc_ptr as *const AtomicIsize).sub(1);
            let count = (*rc).load(Ordering::Relaxed);
            count == 0 || count == 1
        }
    }

    fn get_allocation_ptr(&self) -> *mut u8 {
        if self.is_seamless_slice() {
            (self.capacity_or_alloc_ptr & !ROC_SEAMLESS_SLICE_TAG) as *mut u8
        } else {
            self.bytes
        }
    }
}

impl core::fmt::Debug for RocStr {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.debug_struct("RocStr")
            .field("value", &self.as_str())
            .field("len", &self.len())
            .field("is_small", &self.is_small_str())
            .finish()
    }
}

/// A generic Roc list. Elements are reference-counted and heap-allocated.
///
/// When `ELEMENTS_REFCOUNTED` is true (the default via `RocList<T>`), an extra
/// `ptr_width` bytes are reserved in the allocation header for the element count,
/// matching the Roc runtime's `allocateWithRefcount` layout.
pub type RocList<T> = RocListWith<T, true>;

/// Parameterized list constructor; use `RocList<T>` for refcounted elements.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct RocListWith<T, const ELEMENTS_REFCOUNTED: bool> {
    pub elements: *mut T,
    pub length: usize,
    pub capacity_or_alloc_ptr: usize,
}

impl<T, const ELEMENTS_REFCOUNTED: bool> RocListWith<T, ELEMENTS_REFCOUNTED> {
    #[inline]
    fn header_bytes() -> usize {
        let ptr_width = core::mem::size_of::<usize>();
        let required_space = if ELEMENTS_REFCOUNTED { 2 * ptr_width } else { ptr_width };
        required_space.max(core::mem::align_of::<T>())
    }

    /// Return an empty RocList.
    pub fn empty() -> Self {
        Self {
            elements: core::ptr::null_mut(),
            length: 0,
            capacity_or_alloc_ptr: 0,
        }
    }

    /// Return the number of elements in the list.
    #[inline]
    pub fn len(&self) -> usize {
        self.length
    }

    /// Return true if the list has zero elements.
    #[inline]
    pub fn is_empty(&self) -> bool {
        self.length == 0
    }

    /// Return true if this list is a seamless slice into another allocation.
    /// Slices share the rc slot with their backing allocation; the alloc ptr is
    /// encoded in `capacity_or_alloc_ptr` with the low bit set.
    #[inline]
    pub fn is_seamless_slice(&self) -> bool {
        (self.capacity_or_alloc_ptr & 1) != 0
    }

    /// Resolve `self` to the start of its backing allocation (the element block
    /// just after the rc slot). Returns `null` for empty lists. Handles both
    /// whole-backing and seamless-slice forms.
    fn get_allocation_ptr(&self) -> *mut u8 {
        if self.is_seamless_slice() {
            (self.capacity_or_alloc_ptr & !1) as *mut u8
        } else {
            self.elements as *mut u8
        }
    }

    fn allocation_element_count(&self) -> usize {
        if self.is_seamless_slice() && ELEMENTS_REFCOUNTED {
            let alloc_ptr = self.get_allocation_ptr();
            if alloc_ptr.is_null() {
                return 0;
            }
            unsafe {
                let ptr = alloc_ptr as *const usize;
                *ptr.sub(2)
            }
        } else {
            self.length
        }
    }

    /// Return the list elements as a slice.
    pub fn as_slice(&self) -> &[T] {
        if self.elements.is_null() {
            &[]
        } else {
            unsafe { core::slice::from_raw_parts(self.elements, self.length) }
        }
    }

    /// Return all items in the backing allocation, not just this slice.
    pub fn allocation_items(&self) -> &[T] {
        if self.elements.is_null() {
            &[]
        } else {
            unsafe { core::slice::from_raw_parts(self.get_allocation_ptr() as *const T, self.allocation_element_count()) }
        }
    }

    /// Allocate a new list with space for `length` elements.
    pub fn allocate(length: usize, roc_host: &RocHost) -> Self {
        if length == 0 {
            return Self::empty();
        }
        let align = core::mem::align_of::<T>().max(core::mem::align_of::<usize>());
        let header_bytes = Self::header_bytes();
        let data_bytes = length * core::mem::size_of::<T>();
        let total = data_bytes + header_bytes;
        let base = unsafe { roc_host.alloc(align, total) };
        let data_ptr = unsafe { (base as *mut u8).add(header_bytes) };
        // Write refcount = 1
        unsafe {
            let rc = (data_ptr as *mut isize).sub(1);
            *rc = 1;
        }
        Self {
            elements: data_ptr as *mut T,
            length,
            capacity_or_alloc_ptr: length << 1,
        }
    }

    /// Create a RocList from a slice, copying elements into a new allocation.
    pub fn from_slice(slice: &[T], roc_host: &RocHost) -> Self where T: Copy {
        if slice.is_empty() {
            return Self::empty();
        }
        let list = Self::allocate(slice.len(), roc_host);
        unsafe {
            core::ptr::copy_nonoverlapping(
                slice.as_ptr(),
                list.elements,
                slice.len(),
            );
        }
        list
    }

    /// Decrement the reference count; frees the allocation when it reaches zero.
    pub fn decref(&self, roc_host: &RocHost) {
        if self.elements.is_null() {
            return;
        }
        let alloc_ptr = self.get_allocation_ptr();
        if alloc_ptr.is_null() {
            return;
        }
        let align = core::mem::align_of::<T>().max(core::mem::align_of::<usize>());
        let header_bytes = Self::header_bytes();
        unsafe {
            let rc = (alloc_ptr as *mut AtomicIsize).sub(1);
            if (*rc).load(Ordering::Relaxed) == 0 {
                return; // REFCOUNT_STATIC_DATA — elements are in read-only memory
            }
            let prev = (*rc).fetch_sub(1, Ordering::Relaxed);
            if prev == 1 {
                let base = alloc_ptr.sub(header_bytes) as *mut c_void;
                roc_host.dealloc(base, align);
            }
        }
    }

    /// Increment the reference count by `amount`.
    pub fn incref(&self, amount: isize) {
        if self.elements.is_null() {
            return;
        }
        let alloc_ptr = self.get_allocation_ptr();
        if alloc_ptr.is_null() {
            return;
        }
        unsafe {
            let rc = (alloc_ptr as *mut AtomicIsize).sub(1);
            if (*rc).load(Ordering::Relaxed) == 0 {
                return; // REFCOUNT_STATIC_DATA
            }
            (*rc).fetch_add(amount, Ordering::Relaxed);
        }
    }

    /// Return true if this list has a reference count of exactly one.
    pub fn is_unique(&self) -> bool {
        let alloc_ptr = self.get_allocation_ptr();
        if alloc_ptr.is_null() {
            return true;
        }
        unsafe {
            let rc = (alloc_ptr as *const AtomicIsize).sub(1);
            let count = (*rc).load(Ordering::Relaxed);
            count == 0 || count == 1
        }
    }

    /// Return true if this list's allocation has exactly one counted ref.
    pub fn has_one_ref(&self) -> bool {
        let alloc_ptr = self.get_allocation_ptr();
        if alloc_ptr.is_null() {
            return false;
        }
        unsafe {
            let rc = (alloc_ptr as *const AtomicIsize).sub(1);
            (*rc).load(Ordering::Relaxed) == 1
        }
    }
}

impl<T: core::fmt::Debug, const ELEMENTS_REFCOUNTED: bool> core::fmt::Debug for RocListWith<T, ELEMENTS_REFCOUNTED> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.debug_list().entries(self.as_slice().iter()).finish()
    }
}

/// Element type for __AnonStruct3
#[repr(C)]
#[derive(Clone, Copy)]
pub struct AnonStruct3 {
    pub path: RocStr,
    pub relpath: RocStr,
    pub url: RocStr,
}

const _: () = assert!(core::mem::size_of::<AnonStruct3>() == 72, "AnonStruct3 size mismatch");
const _: () = assert!(core::mem::align_of::<AnonStruct3>() == 8, "AnonStruct3 alignment mismatch");

/// Tag discriminant for Try.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TryType0Tag {
    Err = 0,
    Ok = 1,
}

/// Tag union: Try
#[repr(C)]
#[derive(Clone, Copy)]
pub struct TryType0 {
    pub payload: TryType0Payload,
    pub tag: TryType0Tag,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union TryType0Payload {
    pub err: core::mem::ManuallyDrop<RocStr>,
    pub ok: core::mem::ManuallyDrop<RocList<AnonStruct3>>,
}

const _: () = assert!(core::mem::size_of::<TryType0>() == 32, "TryType0 size mismatch");
const _: () = assert!(core::mem::align_of::<TryType0>() == 8, "TryType0 alignment mismatch");

/// Tag discriminant for Try.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TryType4Tag {
    Err = 0,
    Ok = 1,
}

/// Tag union: Try
#[repr(C)]
#[derive(Clone, Copy)]
pub struct TryType4 {
    pub payload: TryType4Payload,
    pub tag: TryType4Tag,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union TryType4Payload {
    pub err: core::mem::ManuallyDrop<RocStr>,
    pub ok: core::mem::ManuallyDrop<RocStr>,
}

const _: () = assert!(core::mem::size_of::<TryType4>() == 32, "TryType4 size mismatch");
const _: () = assert!(core::mem::align_of::<TryType4>() == 8, "TryType4 alignment mismatch");

/// Tag discriminant for Try.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TryType5Tag {
    Err = 0,
    Ok = 1,
}

/// Tag union: Try
#[repr(C)]
#[derive(Clone, Copy)]
pub struct TryType5 {
    pub payload: TryType5Payload,
    pub tag: TryType5Tag,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union TryType5Payload {
    pub err: core::mem::ManuallyDrop<RocStr>,
    pub ok: core::mem::ManuallyDrop<()>,
}

const _: () = assert!(core::mem::size_of::<TryType5>() == 32, "TryType5 size mismatch");
const _: () = assert!(core::mem::align_of::<TryType5>() == 8, "TryType5 alignment mismatch");

/// Tag discriminant for Try.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TryType7Tag {
    Err = 0,
    Ok = 1,
}

/// Tag union: Try
#[repr(C)]
#[derive(Clone, Copy)]
pub struct TryType7 {
    pub payload: TryType7Payload,
    pub tag: TryType7Tag,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union TryType7Payload {
    pub err: core::mem::ManuallyDrop<IOErr>,
    pub ok: core::mem::ManuallyDrop<()>,
}

const _: () = assert!(core::mem::size_of::<TryType7>() == 40, "TryType7 size mismatch");
const _: () = assert!(core::mem::align_of::<TryType7>() == 8, "TryType7 alignment mismatch");

/// Tag discriminant for IOErr.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum IOErrTag {
    AlreadyExists = 0,
    BrokenPipe = 1,
    Interrupted = 2,
    NotFound = 3,
    Other = 4,
    OutOfMemory = 5,
    PermissionDenied = 6,
    Unsupported = 7,
}

/// Tag union: IOErr
#[repr(C)]
#[derive(Clone, Copy)]
pub struct IOErr {
    pub payload: IOErrPayload,
    pub tag: IOErrTag,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union IOErrPayload {
    pub already_exists: [u8; 0],
    pub broken_pipe: [u8; 0],
    pub interrupted: [u8; 0],
    pub not_found: [u8; 0],
    pub other: core::mem::ManuallyDrop<RocStr>,
    pub out_of_memory: [u8; 0],
    pub permission_denied: [u8; 0],
    pub unsupported: [u8; 0],
}

const _: () = assert!(core::mem::size_of::<IOErr>() == 32, "IOErr size mismatch");
const _: () = assert!(core::mem::align_of::<IOErr>() == 8, "IOErr alignment mismatch");

/// Tag discriminant for Try.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TryType12Tag {
    Err = 0,
    Ok = 1,
}

/// Tag union: Try
#[repr(C)]
#[derive(Clone, Copy)]
pub struct TryType12 {
    pub payload: TryType12Payload,
    pub tag: TryType12Tag,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union TryType12Payload {
    pub err: core::mem::ManuallyDrop<IOErr>,
    pub ok: core::mem::ManuallyDrop<()>,
}

const _: () = assert!(core::mem::size_of::<TryType12>() == 40, "TryType12 size mismatch");
const _: () = assert!(core::mem::align_of::<TryType12>() == 8, "TryType12 alignment mismatch");

/// Tag discriminant for Try.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TryType19Tag {
    Err = 0,
    Ok = 1,
}

/// Tag union: Try
#[repr(C)]
#[derive(Clone, Copy)]
pub struct TryType19 {
    pub payload: TryType19Payload,
    pub tag: TryType19Tag,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union TryType19Payload {
    pub err: core::mem::ManuallyDrop<i32>,
    pub ok: core::mem::ManuallyDrop<()>,
}

const _: () = assert!(core::mem::size_of::<TryType19>() == 8, "TryType19 size mismatch");
const _: () = assert!(core::mem::align_of::<TryType19>() == 4, "TryType19 alignment mismatch");

/// Arguments for SSG.host_find_files!
/// Roc signature: Str => Try(List({ path : Str, relpath : Str, url : Str }), Str)
/// Refcounted fields are owned by the hosted function.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SSGHostFindFilesArgs {
    pub arg0: RocStr,
}

/// Arguments for SSG.host_parse_markdown!
/// Roc signature: Str => Try(Str, Str)
/// Refcounted fields are owned by the hosted function.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SSGHostParseMarkdownArgs {
    pub arg0: RocStr,
}

/// Arguments for SSG.host_write_file!
/// Roc signature: Str, Str, Str => Try({}, Str)
/// Refcounted fields are owned by the hosted function.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SSGHostWriteFileArgs {
    pub arg0: RocStr,
    pub arg1: RocStr,
    pub arg2: RocStr,
}

/// Arguments for Stderr.line!
/// Roc signature: Str => Try({}, [StderrErr(IOErr)])
/// Refcounted fields are owned by the hosted function.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct StderrLineArgs {
    pub arg0: RocStr,
}

/// Arguments for Stderr.write!
/// Roc signature: Str => Try({}, [StderrErr(IOErr)])
/// Refcounted fields are owned by the hosted function.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct StderrWriteArgs {
    pub arg0: RocStr,
}

/// Arguments for Stderr.write_bytes!
/// Roc signature: List(U8) => Try({}, [StderrErr(IOErr)])
/// Refcounted fields are owned by the hosted function.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct StderrWriteBytesArgs {
    pub arg0: RocListWith<u8, false>,
}

// =============================================================================
// Semantic Type Aliases
// =============================================================================

pub type SSGHostFindFilesResult = TryType0;
pub type SSGHostFindFilesResultPayload = TryType0Payload;
pub type SSGHostFindFilesResultTag = TryType0Tag;
pub type SSGHostFindFilesOk = AnonStruct3;
pub type SSGHostParseMarkdownResult = TryType4;
pub type SSGHostParseMarkdownResultPayload = TryType4Payload;
pub type SSGHostParseMarkdownResultTag = TryType4Tag;
pub type SSGHostWriteFileResult = TryType5;
pub type SSGHostWriteFileResultPayload = TryType5Payload;
pub type SSGHostWriteFileResultTag = TryType5Tag;
pub type StderrLineResult = TryType7;
pub type StderrLineResultPayload = TryType7Payload;
pub type StderrLineResultTag = TryType7Tag;
pub type StderrIOErr = IOErr;
pub type StderrIOErrPayload = IOErrPayload;
pub type StderrIOErrTag = IOErrTag;
pub type StderrWriteResult = TryType7;
pub type StderrWriteResultPayload = TryType7Payload;
pub type StderrWriteResultTag = TryType7Tag;
pub type StderrWriteBytesResult = TryType12;
pub type StderrWriteBytesResultPayload = TryType12Payload;
pub type StderrWriteBytesResultTag = TryType12Tag;

// =============================================================================
// Generated Refcount Helpers
// =============================================================================

/// Recursively decrement Roc-owned payloads in TryType0.
pub fn decref_try_type0(value: TryType0, roc_host: &RocHost) {
    let _ = roc_host;
    match value.tag {
        TryType0Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            payload.decref(roc_host);
        },
        TryType0Tag::Ok => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.ok);
            {
                let list = payload;
                if list.has_one_ref() {
                    for item in list.allocation_items() {
                            decref_anon_struct3((*item), roc_host);
                    }
                }
                list.decref(roc_host);
            }
        },
    }
}

/// Increment Roc-owned payloads in TryType0.
pub fn incref_try_type0(value: TryType0, amount: isize) {
    let _ = amount;
    match value.tag {
        TryType0Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            payload.incref(amount);
        },
        TryType0Tag::Ok => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.ok);
            payload.incref(amount);
        },
    }
}

/// Recursively decrement Roc-owned fields in AnonStruct3.
pub fn decref_anon_struct3(value: AnonStruct3, roc_host: &RocHost) {
    value.path.decref(roc_host);
    value.relpath.decref(roc_host);
    value.url.decref(roc_host);
}

/// Increment Roc-owned fields in AnonStruct3.
pub fn incref_anon_struct3(value: AnonStruct3, amount: isize) {
    value.path.incref(amount);
    value.relpath.incref(amount);
    value.url.incref(amount);
}

/// Recursively decrement Roc-owned payloads in TryType4.
pub fn decref_try_type4(value: TryType4, roc_host: &RocHost) {
    let _ = roc_host;
    match value.tag {
        TryType4Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            payload.decref(roc_host);
        },
        TryType4Tag::Ok => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.ok);
            payload.decref(roc_host);
        },
    }
}

/// Increment Roc-owned payloads in TryType4.
pub fn incref_try_type4(value: TryType4, amount: isize) {
    let _ = amount;
    match value.tag {
        TryType4Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            payload.incref(amount);
        },
        TryType4Tag::Ok => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.ok);
            payload.incref(amount);
        },
    }
}

/// Recursively decrement Roc-owned payloads in TryType5.
pub fn decref_try_type5(value: TryType5, roc_host: &RocHost) {
    let _ = roc_host;
    match value.tag {
        TryType5Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            payload.decref(roc_host);
        },
        TryType5Tag::Ok => {},
    }
}

/// Increment Roc-owned payloads in TryType5.
pub fn incref_try_type5(value: TryType5, amount: isize) {
    let _ = amount;
    match value.tag {
        TryType5Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            payload.incref(amount);
        },
        TryType5Tag::Ok => {},
    }
}

/// Recursively decrement Roc-owned payloads in TryType7.
pub fn decref_try_type7(value: TryType7, roc_host: &RocHost) {
    let _ = roc_host;
    match value.tag {
        TryType7Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            decref_ioerr(payload, roc_host);
        },
        TryType7Tag::Ok => {},
    }
}

/// Increment Roc-owned payloads in TryType7.
pub fn incref_try_type7(value: TryType7, amount: isize) {
    let _ = amount;
    match value.tag {
        TryType7Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            incref_ioerr(payload, amount);
        },
        TryType7Tag::Ok => {},
    }
}

/// Recursively decrement Roc-owned payloads in IOErr.
pub fn decref_ioerr(value: IOErr, roc_host: &RocHost) {
    let _ = roc_host;
    match value.tag {
        IOErrTag::AlreadyExists => {},
        IOErrTag::BrokenPipe => {},
        IOErrTag::Interrupted => {},
        IOErrTag::NotFound => {},
        IOErrTag::Other => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.other);
            payload.decref(roc_host);
        },
        IOErrTag::OutOfMemory => {},
        IOErrTag::PermissionDenied => {},
        IOErrTag::Unsupported => {},
    }
}

/// Increment Roc-owned payloads in IOErr.
pub fn incref_ioerr(value: IOErr, amount: isize) {
    let _ = amount;
    match value.tag {
        IOErrTag::AlreadyExists => {},
        IOErrTag::BrokenPipe => {},
        IOErrTag::Interrupted => {},
        IOErrTag::NotFound => {},
        IOErrTag::Other => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.other);
            payload.incref(amount);
        },
        IOErrTag::OutOfMemory => {},
        IOErrTag::PermissionDenied => {},
        IOErrTag::Unsupported => {},
    }
}

/// Recursively decrement Roc-owned payloads in TryType12.
pub fn decref_try_type12(value: TryType12, roc_host: &RocHost) {
    let _ = roc_host;
    match value.tag {
        TryType12Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            decref_ioerr(payload, roc_host);
        },
        TryType12Tag::Ok => {},
    }
}

/// Increment Roc-owned payloads in TryType12.
pub fn incref_try_type12(value: TryType12, amount: isize) {
    let _ = amount;
    match value.tag {
        TryType12Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            incref_ioerr(payload, amount);
        },
        TryType12Tag::Ok => {},
    }
}

/// Recursively decrement Roc-owned payloads in TryType19.
pub fn decref_try_type19(value: TryType19, roc_host: &RocHost) {
    let _ = roc_host;
    match value.tag {
        TryType19Tag::Err => {},
        TryType19Tag::Ok => {},
    }
}

/// Increment Roc-owned payloads in TryType19.
pub fn incref_try_type19(value: TryType19, amount: isize) {
    let _ = amount;
    match value.tag {
        TryType19Tag::Err => {},
        TryType19Tag::Ok => {},
    }
}


// =============================================================================
// Runtime Symbols
//
// The host defines these linker symbols. Compiled Roc code calls them directly.
// =============================================================================

#[allow(improper_ctypes)]
unsafe extern "C" {
    pub fn roc_alloc(length: usize, alignment: usize) -> *mut c_void;
    pub fn roc_dealloc(ptr: *mut c_void, alignment: usize);
    pub fn roc_realloc(ptr: *mut c_void, new_length: usize, alignment: usize) -> *mut c_void;
    pub fn roc_dbg(bytes: *const u8, len: usize);
    pub fn roc_expect_failed(bytes: *const u8, len: usize);
    pub fn roc_crashed(bytes: *const u8, len: usize);
}

// =============================================================================
// Hosted Symbols
//
// The platform host must export these symbols with the exact direct C ABI signatures.
// Refcounted arguments are owned by the hosted function.
// =============================================================================

#[allow(improper_ctypes)]
unsafe extern "C" {
    /// Hosted symbol for SSG.host_find_files!
    /// Roc signature: Str => Try(List({ path : Str, relpath : Str, url : Str }), Str)
    pub fn hosted_ssg_find_files(arg0: RocStr) -> TryType0;

    /// Hosted symbol for SSG.host_parse_markdown!
    /// Roc signature: Str => Try(Str, Str)
    pub fn hosted_ssg_parse_markdown(arg0: RocStr) -> TryType4;

    /// Hosted symbol for SSG.host_write_file!
    /// Roc signature: Str, Str, Str => Try({}, Str)
    pub fn hosted_ssg_write_file(arg0: RocStr, arg1: RocStr, arg2: RocStr) -> TryType5;

    /// Hosted symbol for Stderr.line!
    /// Roc signature: Str => Try({}, [StderrErr(IOErr)])
    pub fn hosted_stderr_line(arg0: RocStr) -> TryType7;

    /// Hosted symbol for Stderr.write!
    /// Roc signature: Str => Try({}, [StderrErr(IOErr)])
    pub fn hosted_stderr_write(arg0: RocStr) -> TryType7;

    /// Hosted symbol for Stderr.write_bytes!
    /// Roc signature: List(U8) => Try({}, [StderrErr(IOErr)])
    pub fn hosted_stderr_write_bytes(arg0: RocListWith<u8, false>) -> TryType12;

}

/// Default memory management functions for Roc platform helpers.
///
/// Memory layout: each allocation prepends size metadata so that dealloc/realloc
/// can recover the original allocation size because `roc_dealloc` receives no length.
pub struct DefaultAllocators;

impl DefaultAllocators {
    /// Allocate memory using the Rust global allocator.
    pub extern "C" fn roc_alloc(_roc_host: *mut RocHost, length: usize, alignment: usize) -> *mut c_void {
        unsafe {
            let min_alignment = alignment.max(core::mem::align_of::<usize>());
            let size_storage_bytes = min_alignment;
            let total_size = length + size_storage_bytes;

            debug_assert!(min_alignment.is_power_of_two(), "alignment must be a power of two");
            let layout = Layout::from_size_align_unchecked(total_size, min_alignment);
            let base_ptr = std::alloc::alloc(layout);
            if base_ptr.is_null() {
                eprintln!("roc_alloc: out of memory");
                std::process::exit(1);
            }

            let size_ptr = base_ptr.add(size_storage_bytes).sub(core::mem::size_of::<usize>()) as *mut usize;
            *size_ptr = total_size;

            base_ptr.add(size_storage_bytes) as *mut c_void
        }
    }

    /// Free memory previously allocated by `roc_alloc`.
    pub extern "C" fn roc_dealloc(_roc_host: *mut RocHost, ptr: *mut c_void, alignment: usize) {
        unsafe {
            let min_alignment = alignment.max(core::mem::align_of::<usize>());
            let size_storage_bytes = min_alignment;

            let size_ptr = (ptr as *const u8).sub(core::mem::size_of::<usize>()) as *const usize;
            let total_size = *size_ptr;

            let base_ptr = (ptr as *mut u8).sub(size_storage_bytes);
            debug_assert!(min_alignment.is_power_of_two(), "alignment must be a power of two");
            let layout = Layout::from_size_align_unchecked(total_size, min_alignment);
            std::alloc::dealloc(base_ptr, layout);
        }
    }

    /// Reallocate memory, preserving existing user data.
    pub extern "C" fn roc_realloc(_roc_host: *mut RocHost, ptr: *mut c_void, new_length: usize, alignment: usize) -> *mut c_void {
        unsafe {
            let min_alignment = alignment.max(core::mem::align_of::<usize>());
            let size_storage_bytes = min_alignment;

            let old_size_ptr = (ptr as *const u8).sub(core::mem::size_of::<usize>()) as *const usize;
            let old_total_size = *old_size_ptr;
            let old_base_ptr = (ptr as *mut u8).sub(size_storage_bytes);

            let new_total_size = new_length + size_storage_bytes;
            debug_assert!(min_alignment.is_power_of_two(), "alignment must be a power of two");
            let old_layout = Layout::from_size_align_unchecked(old_total_size, min_alignment);
            let new_base_ptr = std::alloc::realloc(old_base_ptr, old_layout, new_total_size);
            if new_base_ptr.is_null() {
                eprintln!("roc_realloc: out of memory");
                std::process::exit(1);
            }

            let new_user_ptr = new_base_ptr.add(size_storage_bytes);
            let new_size_ptr = new_user_ptr.sub(core::mem::size_of::<usize>()) as *mut usize;
            *new_size_ptr = new_total_size;
            new_user_ptr as *mut c_void
        }
    }
}

/// Default handlers for dbg, expect-failed, and crash.
pub struct DefaultHandlers;

impl DefaultHandlers {
    /// Print a `dbg` expression to stderr.
    pub extern "C" fn roc_dbg(_roc_host: *mut RocHost, bytes: *const u8, len: usize) {
        unsafe {
            let msg = core::slice::from_raw_parts(bytes, len);
            let msg = core::str::from_utf8_unchecked(msg);
            eprintln!("[ROC DBG] {}", msg);
        }
    }

    /// Print a failed `expect` to stderr.
    pub extern "C" fn roc_expect_failed(_roc_host: *mut RocHost, bytes: *const u8, len: usize) {
        unsafe {
            let msg = core::slice::from_raw_parts(bytes, len);
            let msg = core::str::from_utf8_unchecked(msg);
            eprintln!("[ROC EXPECT] {}", msg);
        }
    }

    /// Print a `crash` message to stderr and exit.
    pub extern "C" fn roc_crashed(_roc_host: *mut RocHost, bytes: *const u8, len: usize) {
        unsafe {
            let msg = core::slice::from_raw_parts(bytes, len);
            let msg = core::str::from_utf8_unchecked(msg);
            eprintln!("[ROC CRASHED] {}", msg);
            std::process::exit(1);
        }
    }
}

/// Create a host-internal helper context with default memory management and handlers.
///
/// This is only for helper functions in this generated file. It is not passed to
/// compiled Roc code, which uses the direct symbol ABI declared above.
pub fn make_roc_host(env: *mut c_void) -> RocHost {
    RocHost {
        env,
        roc_alloc: DefaultAllocators::roc_alloc,
        roc_dealloc: DefaultAllocators::roc_dealloc,
        roc_realloc: DefaultAllocators::roc_realloc,
        roc_dbg: DefaultHandlers::roc_dbg,
        roc_expect_failed: DefaultHandlers::roc_expect_failed,
        roc_crashed: DefaultHandlers::roc_crashed,
    }
}

// =============================================================================
// Provided Symbols
//
// Roc exports these symbols from the app with their natural C ABI signatures.
// =============================================================================

#[allow(improper_ctypes)]
unsafe extern "C" {
    /// Entrypoint: main_for_host!
    pub fn roc_main(arg0: RocList<RocStr>) -> i32;

}
