name: Nightly configuration
on:
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  configuration:
    uses: lukewilliamboswell/roc-automation/.github/workflows/check-config.yml@c365856d92d0ed81f26443c23a31777ae23fa390
